package com.wonderlife.mapper;

import com.wonderlife.domain.EducationRegionSummary;
import com.wonderlife.domain.SchoolInfo;
import org.apache.ibatis.annotations.*;
import java.time.LocalDate;
import java.util.List;

@Mapper public interface EducationStatisticsMapper{
 @Select("SELECT id FROM tools_education_collection_runs WHERE business_date=#{date} AND source=#{source}") Long runId(@Param("date")LocalDate date,@Param("source")String source);
 @Select("SELECT status FROM tools_education_collection_runs WHERE id=#{id}") String runStatus(long id);
 @Insert("INSERT INTO tools_education_collection_runs(business_date,source,status) VALUES(#{date},#{source},'RUNNING')") @Options(useGeneratedKeys=true,keyProperty="row.id") void startRun(@Param("date")LocalDate date,@Param("source")String source,@Param("row")MutableId row);
 @Update("UPDATE tools_education_collection_runs SET status='RUNNING',started_at=CURRENT_TIMESTAMP,finished_at=NULL,item_count=0,error_message=NULL WHERE id=#{id}") void restartRun(long id);
 @Update("UPDATE tools_education_collection_runs SET status='SUCCESS',finished_at=CURRENT_TIMESTAMP,item_count=#{count},error_message=NULL WHERE id=#{id}") void finishRun(@Param("id")long id,@Param("count")int count);
 @Update("UPDATE tools_education_collection_runs SET status='FAILED',finished_at=CURRENT_TIMESTAMP,error_message=#{message} WHERE id=#{id}") void failRun(@Param("id")long id,@Param("message")String message);
 @Insert("INSERT INTO tools_education_schools(education_office_code,school_code,education_office_name,school_name,school_kind,location_name,address,coeducation_type,homepage_url,foundation_type,status,opened_on,last_seen_date) VALUES(#{s.educationOfficeCode},#{s.schoolCode},#{s.educationOfficeName},#{s.schoolName},#{s.schoolKind},#{s.locationName},#{s.address},#{s.coeducationType},#{s.homepageUrl},#{s.foundationType},#{s.status},STR_TO_DATE(NULLIF(#{s.openedOn},''),'%Y%m%d'),#{date}) ON DUPLICATE KEY UPDATE education_office_name=VALUES(education_office_name),school_name=VALUES(school_name),school_kind=VALUES(school_kind),location_name=VALUES(location_name),address=VALUES(address),coeducation_type=VALUES(coeducation_type),homepage_url=VALUES(homepage_url),foundation_type=VALUES(foundation_type),status=VALUES(status),opened_on=VALUES(opened_on),last_seen_date=VALUES(last_seen_date)") void upsertSchool(@Param("s")SchoolInfo school,@Param("date")LocalDate date);
 @Insert("<script>INSERT INTO tools_education_schools(education_office_code,school_code,education_office_name,school_name,school_kind,location_name,address,coeducation_type,homepage_url,foundation_type,status,opened_on,last_seen_date) VALUES <foreach collection='schools' item='s' separator=','>(#{s.educationOfficeCode},#{s.schoolCode},#{s.educationOfficeName},#{s.schoolName},#{s.schoolKind},#{s.locationName},#{s.address},#{s.coeducationType},#{s.homepageUrl},#{s.foundationType},#{s.status},STR_TO_DATE(NULLIF(#{s.openedOn},''),'%Y%m%d'),#{date})</foreach> ON DUPLICATE KEY UPDATE education_office_name=VALUES(education_office_name),school_name=VALUES(school_name),school_kind=VALUES(school_kind),location_name=VALUES(location_name),address=VALUES(address),coeducation_type=VALUES(coeducation_type),homepage_url=VALUES(homepage_url),foundation_type=VALUES(foundation_type),status=VALUES(status),opened_on=VALUES(opened_on),last_seen_date=VALUES(last_seen_date)</script>") void upsertSchools(@Param("schools")List<SchoolInfo> schools,@Param("date")LocalDate date);
 @Select("SELECT education_office_code,school_code,education_office_name,school_name,school_kind,location_name,address,coeducation_type,homepage_url,foundation_type,status,DATE_FORMAT(opened_on,'%Y-%m-%d') opened_on FROM tools_education_schools WHERE school_name LIKE CONCAT('%',#{name},'%') ORDER BY school_name LIMIT 20") List<SchoolInfo> search(String name);
 @Select("SELECT education_office_code,school_code,education_office_name,school_name,school_kind,location_name,address,coeducation_type,homepage_url,foundation_type,status,DATE_FORMAT(opened_on,'%Y-%m-%d') opened_on FROM tools_education_schools WHERE education_office_code=#{office} AND school_code=#{school}") SchoolInfo find(@Param("office")String office,@Param("school")String school);
 @Select("SELECT education_office_name region,school_kind,COUNT(*) school_count FROM tools_education_schools GROUP BY education_office_name,school_kind ORDER BY education_office_name,school_kind") List<EducationRegionSummary> summaries();
 @Select("SELECT MAX(last_seen_date) FROM tools_education_schools") LocalDate latestDate();
 @Select("SELECT s.education_office_code office,s.school_code school,s.school_name name FROM tools_education_schools s WHERE EXISTS(SELECT 1 FROM tools_schoolinfo_school_links l JOIN tools_schoolinfo_metrics m ON m.school_code=l.schoolinfo_code WHERE l.education_office_code=s.education_office_code AND l.neis_school_code=s.school_code) OR EXISTS(SELECT 1 FROM tools_school_meals d WHERE d.education_office_code=s.education_office_code AND d.school_code=s.school_code AND d.meal_date BETWEEN DATE_SUB(CURRENT_DATE,INTERVAL 365 DAY) AND DATE_ADD(CURRENT_DATE,INTERVAL 90 DAY)) OR EXISTS(SELECT 1 FROM tools_school_schedules e WHERE e.education_office_code=s.education_office_code AND e.school_code=s.school_code AND e.event_date BETWEEN DATE_SUB(CURRENT_DATE,INTERVAL 365 DAY) AND DATE_ADD(CURRENT_DATE,INTERVAL 90 DAY)) ORDER BY s.education_office_code,s.school_code LIMIT 50000")
 List<SchoolPage> indexableSchools();
 record SchoolPage(String office,String school,String name){}
 class MutableId{public long id;public long getId(){return id;}public void setId(long id){this.id=id;}}
}
