package com.wonderlife.mapper;

import com.wonderlife.domain.PublicPriceRow;
import com.wonderlife.domain.StoredPublicPriceRow;
import org.apache.ibatis.annotations.*;
import java.time.LocalDate;
import java.util.List;

@Mapper public interface PublicPriceStorageMapper{
 @Select("SELECT status FROM tools_public_price_collection_runs WHERE source_type=#{source} AND business_date=#{date}") String runStatus(@Param("source")String source,@Param("date")LocalDate date);
 @Select("SELECT COUNT(*)>0 FROM tools_public_price_collection_runs WHERE source_type=#{source} AND business_date=#{date} AND status='RUNNING' AND started_at>=CURRENT_TIMESTAMP - INTERVAL 30 MINUTE") boolean runIsActive(@Param("source")String source,@Param("date")LocalDate date);
 @Insert("INSERT INTO tools_public_price_collection_runs(source_type,business_date,status) VALUES(#{source},#{date},'RUNNING') ON DUPLICATE KEY UPDATE started_at=CURRENT_TIMESTAMP,finished_at=NULL,status='RUNNING',item_count=0,error_message=NULL") void startRun(@Param("source")String source,@Param("date")LocalDate date);
 @Update("UPDATE tools_public_price_collection_runs SET finished_at=CURRENT_TIMESTAMP,status='SUCCESS',item_count=#{count},error_message=NULL WHERE source_type=#{source} AND business_date=#{date}") void finishRun(@Param("source")String source,@Param("date")LocalDate date,@Param("count")int count);
 @Update("UPDATE tools_public_price_collection_runs SET finished_at=CURRENT_TIMESTAMP,status='FAILED',error_message=#{message} WHERE source_type=#{source} AND business_date=#{date}") void failRun(@Param("source")String source,@Param("date")LocalDate date,@Param("message")String message);
 @Insert({"<script>","INSERT INTO tools_public_price_history(source_type,collected_date,price_date,market_type,category_code,category_name,item_code,item_name,variety_code,variety_name,grade_code,grade_name,region_code,region_name,market_code,market_name,unit,unit_size,price,normalized_price,min_price,average_price,max_price) VALUES","<foreach collection='rows' item='r' separator=','>","(#{r.sourceType},#{r.collectedDate},#{r.priceDate},#{r.marketType},#{r.categoryCode},#{r.categoryName},#{r.itemCode},#{r.itemName},#{r.varietyCode},#{r.varietyName},#{r.gradeCode},#{r.gradeName},#{r.regionCode},#{r.regionName},#{r.marketCode},#{r.marketName},#{r.unit},#{r.unitSize},#{r.price},#{r.normalizedPrice},#{r.minPrice},#{r.averagePrice},#{r.maxPrice})","</foreach>","ON DUPLICATE KEY UPDATE collected_date=VALUES(collected_date),category_name=VALUES(category_name),item_name=VALUES(item_name),variety_name=VALUES(variety_name),grade_name=VALUES(grade_name),region_name=VALUES(region_name),market_name=VALUES(market_name),price=VALUES(price),normalized_price=VALUES(normalized_price),min_price=VALUES(min_price),average_price=VALUES(average_price),max_price=VALUES(max_price)","</script>"}) void upsertBatch(@Param("rows")List<StoredPublicPriceRow> rows);
 @Select({"<script>","SELECT DATE_FORMAT(price_date,'%Y%m%d') date,market_type,category_code,category_name,item_code,item_name,variety_code,variety_name,grade_code,grade_name,region_code,region_name,market_code,market_name,CONCAT(unit_size,unit) unit,price,normalized_price,min_price,average_price,max_price FROM tools_public_price_history WHERE source_type=#{source} AND price_date BETWEEN #{from} AND #{to}","<if test='itemCode != null and itemCode != &quot;&quot;'> AND item_code=#{itemCode}</if>","<if test='regionCode != null and regionCode != &quot;&quot;'> AND region_code=#{regionCode}</if>","ORDER BY price_date DESC,item_name,region_name,market_name LIMIT 500","</script>"}) List<PublicPriceRow> find(@Param("source")String source,@Param("from")LocalDate from,@Param("to")LocalDate to,@Param("itemCode")String itemCode,@Param("regionCode")String regionCode);
 @Select({"<script>","SELECT COUNT(*) FROM tools_public_price_history WHERE source_type=#{source} AND price_date BETWEEN #{from} AND #{to}","<if test='itemCode != null and itemCode != &quot;&quot;'> AND item_code=#{itemCode}</if>","<if test='regionCode != null and regionCode != &quot;&quot;'> AND region_code=#{regionCode}</if>","</script>"}) int count(@Param("source")String source,@Param("from")LocalDate from,@Param("to")LocalDate to,@Param("itemCode")String itemCode,@Param("regionCode")String regionCode);
 @Select("SELECT MAX(price_date) FROM tools_public_price_history WHERE source_type=#{source}") LocalDate latestPriceDate(String source);
 @Select("SELECT COUNT(*) FROM tools_public_price_history WHERE source_type=#{source} AND collected_date=#{date}") int collectedCount(@Param("source")String source,@Param("date")LocalDate date);
}
