package com.wonderlife.mapper;

import org.apache.ibatis.annotations.*;
import java.math.BigDecimal;
import java.util.List;

@Mapper public interface SchoolInfoDisclosureMapper{
 @Select("SELECT next_scope_index FROM tools_schoolinfo_batch_state WHERE id=1") int nextIndex();
 @Update("UPDATE tools_schoolinfo_batch_state SET last_started_at=CURRENT_TIMESTAMP,last_status='RUNNING',last_error=NULL WHERE id=1") void start();
 @Update("UPDATE tools_schoolinfo_batch_state SET next_scope_index=#{next},completed_cycles=completed_cycles+#{cycle},last_finished_at=CURRENT_TIMESTAMP,last_status='SUCCESS' WHERE id=1") void finish(@Param("next")int next,@Param("cycle")int cycle);
 @Update("UPDATE tools_schoolinfo_batch_state SET next_scope_index=#{next},last_finished_at=CURRENT_TIMESTAMP,last_status='FAILED',last_error=#{error} WHERE id=1") void fail(@Param("next")int next,@Param("error")String error);
 @Insert("INSERT INTO tools_schoolinfo_disclosures(api_type,publication_year,school_code,row_key,school_kind_code,region_code,region_name,school_name,payload) VALUES(#{type},#{year},#{school},#{rowKey},#{kind},#{region},#{regionName},#{schoolName},CAST(#{payload} AS JSON)) ON DUPLICATE KEY UPDATE school_kind_code=VALUES(school_kind_code),region_code=VALUES(region_code),region_name=VALUES(region_name),school_name=VALUES(school_name),payload=VALUES(payload),collected_at=CURRENT_TIMESTAMP") void upsert(@Param("type")String type,@Param("year")int year,@Param("school")String school,@Param("rowKey")String rowKey,@Param("kind")String kind,@Param("region")String region,@Param("regionName")String regionName,@Param("schoolName")String schoolName,@Param("payload")String payload);
 @Insert("INSERT INTO tools_schoolinfo_metrics(publication_year,school_code,region_code,school_kind_code,metric_code,metric_value) VALUES(#{year},#{school},#{region},#{kind},#{metric},#{value}) ON DUPLICATE KEY UPDATE region_code=VALUES(region_code),school_kind_code=VALUES(school_kind_code),metric_value=VALUES(metric_value),collected_at=CURRENT_TIMESTAMP") void upsertMetric(@Param("year")int year,@Param("school")String school,@Param("region")String region,@Param("kind")String kind,@Param("metric")String metric,@Param("value")BigDecimal value);
 @Select("SELECT region_code region,metric_code metric,CASE WHEN metric_code IN ('students_per_class','students_per_teacher','books_per_student','meal_rate') THEN AVG(metric_value) ELSE SUM(metric_value) END value,COUNT(DISTINCT school_code) school_count FROM tools_schoolinfo_metrics WHERE publication_year=#{year} GROUP BY region_code,metric_code ORDER BY region_code,metric_code") List<MetricSummary> summaries(int year);
 @Select("SELECT MAX(publication_year) FROM tools_schoolinfo_metrics") Integer latestYear();
 @Select("SELECT publication_year year,metric_code metric,metric_value value FROM tools_schoolinfo_metrics WHERE school_code=#{school} ORDER BY publication_year DESC,metric_code") List<SchoolMetric> schoolMetrics(String school);
 @Insert("INSERT INTO tools_schoolinfo_school_links(schoolinfo_code,education_office_code,neis_school_code) SELECT #{code},MIN(education_office_code),MIN(school_code) FROM tools_education_schools WHERE school_name=#{name} AND education_office_name=#{office} AND school_kind=CASE #{kind} WHEN '02' THEN '초등학교' WHEN '03' THEN '중학교' WHEN '04' THEN '고등학교' WHEN '05' THEN '특수학교' WHEN '07' THEN '각종학교' ELSE '' END HAVING COUNT(*)=1 ON DUPLICATE KEY UPDATE education_office_code=VALUES(education_office_code),neis_school_code=VALUES(neis_school_code),matched_at=CURRENT_TIMESTAMP")
 void linkSchool(@Param("code")String code,@Param("name")String name,@Param("office")String office,@Param("kind")String kind);
 @Select("SELECT m.publication_year year,m.metric_code metric,m.metric_value value FROM tools_schoolinfo_metrics m JOIN tools_schoolinfo_school_links l ON l.schoolinfo_code=m.school_code WHERE l.education_office_code=#{office} AND l.neis_school_code=#{school} ORDER BY m.publication_year DESC,m.metric_code")
 List<SchoolMetric> linkedMetrics(@Param("office")String office,@Param("school")String school);
 @Select("<script>SELECT api_type type,publication_year year,school_code school,school_name name,region_name region,payload,collected_at FROM tools_schoolinfo_disclosures WHERE publication_year=#{year}<if test='type != null and type != &quot;&quot;'> AND api_type=#{type}</if><if test='region != null and region != &quot;&quot;'> AND region_code LIKE CONCAT(#{region},'%')</if><if test='name != null and name != &quot;&quot;'> AND school_name LIKE CONCAT('%',#{name},'%')</if> ORDER BY api_type,school_code,row_key LIMIT #{limit} OFFSET #{offset}</script>")
 List<DisclosureRow> browse(@Param("year")int year,@Param("type")String type,@Param("region")String region,@Param("name")String name,@Param("limit")int limit,@Param("offset")int offset);
 @Select("<script>SELECT COUNT(*) FROM tools_schoolinfo_disclosures WHERE publication_year=#{year}<if test='type != null and type != &quot;&quot;'> AND api_type=#{type}</if><if test='region != null and region != &quot;&quot;'> AND region_code LIKE CONCAT(#{region},'%')</if><if test='name != null and name != &quot;&quot;'> AND school_name LIKE CONCAT('%',#{name},'%')</if></script>")
 long browseCount(@Param("year")int year,@Param("type")String type,@Param("region")String region,@Param("name")String name);
 @Select("SELECT next_scope_index next_index,completed_cycles,last_started_at,last_finished_at,last_status FROM tools_schoolinfo_batch_state WHERE id=1") BatchStatus status();
 record MetricSummary(String region,String metric,BigDecimal value,long schoolCount){}
 record BatchStatus(int nextIndex,int completedCycles,String lastStartedAt,String lastFinishedAt,String lastStatus){}
 record SchoolMetric(int year,String metric,BigDecimal value){}
 record DisclosureRow(String type,int year,String school,String name,String region,String payload,String collectedAt){}
 @Delete("DELETE m FROM tools_schoolinfo_metrics m JOIN tools_schoolinfo_disclosures d ON d.school_code=m.school_code AND d.publication_year=m.publication_year AND d.api_type=m.source_api_type WHERE d.api_type=#{type} AND d.publication_year=#{year} AND d.scope_region_code=#{region} AND d.scope_kind_code=#{kind}")
 void deleteScopeMetrics(@Param("type")String type,@Param("year")int year,@Param("region")String region,@Param("kind")String kind);
 @Delete("DELETE FROM tools_schoolinfo_disclosures WHERE api_type=#{type} AND publication_year=#{year} AND scope_region_code=#{region} AND scope_kind_code=#{kind}")
 void deleteScope(@Param("type")String type,@Param("year")int year,@Param("region")String region,@Param("kind")String kind);
 @Insert("<script>INSERT INTO tools_schoolinfo_disclosures(api_type,publication_year,school_code,row_key,school_kind_code,region_code,region_name,school_name,payload,scope_region_code,scope_kind_code) VALUES <foreach collection='rows' item='r' separator=','>(#{r.type},#{r.year},#{r.school},#{r.rowKey},#{r.kind},#{r.region},#{r.regionName},#{r.schoolName},CAST(#{r.payload} AS JSON),#{r.scopeRegion},#{r.scopeKind})</foreach> ON DUPLICATE KEY UPDATE payload=VALUES(payload),region_code=VALUES(region_code),school_name=VALUES(school_name),scope_region_code=VALUES(scope_region_code),scope_kind_code=VALUES(scope_kind_code),collected_at=CURRENT_TIMESTAMP</script>")
 void upsertRows(@Param("rows")List<RawInput> rows);
 @Insert("<script>INSERT INTO tools_schoolinfo_metrics(publication_year,school_code,region_code,school_kind_code,metric_code,metric_value,source_api_type) VALUES <foreach collection='rows' item='r' separator=','>(#{r.year},#{r.school},#{r.region},#{r.kind},#{r.metric},#{r.value},#{r.type})</foreach> ON DUPLICATE KEY UPDATE metric_value=IF(source_api_type='09' AND VALUES(source_api_type) IN ('22','63'),metric_value,VALUES(metric_value)),source_api_type=IF(source_api_type='09' AND VALUES(source_api_type) IN ('22','63'),source_api_type,VALUES(source_api_type)),collected_at=CURRENT_TIMESTAMP</script>")
 void upsertMetricRows(@Param("rows")List<MetricInput> rows);
 record RawInput(String type,int year,String school,String rowKey,String kind,String region,String regionName,String schoolName,String payload,String scopeRegion,String scopeKind){}
 record MetricInput(int year,String school,String region,String kind,String metric,BigDecimal value,String type){}
}
