import {useEffect,useMemo,useState,type ReactNode} from 'react'
import {carOwnershipCost,earlyRepayment,housingRentComparison,leaveIncome,monthlyBudget,movingCost,repaymentCapacity,retirementEstimate,won,num} from './calculations'
import {focusNumericInput} from './numericInput'

type Props={id:string;title:string;restoreInput?:Record<string,unknown>|null;onCalculated:(title:string,input:unknown,result:unknown)=>void;member:boolean;onNavigate?:(id:string,input?:Record<string,unknown>)=>void}
type Values=Record<string,string>
type CalcResult={main:string;lines:[string,string][];note:string;raw:Record<string,unknown>}
const n=(value:string)=>Number(value.replaceAll(',',''))||0
const grouped=(value:string)=>{const raw=value.replaceAll(',','').replace(/[^0-9.-]/g,'');if(!raw)return'';const [integer,decimal]=raw.split('.');return Number(integer||0).toLocaleString('ko-KR')+(raw.includes('.')?'.'+(decimal??''):'')}
function Field({label,value,onChange,type='number',children}:{label:string;value?:string;onChange?:(value:string)=>void;type?:string;children?:ReactNode}){const numeric=type==='number';return <label className="field"><span>{label}</span>{children||<input type={numeric?'text':type} inputMode={numeric?'decimal':undefined} value={numeric?grouped(value||''):value||''} onFocus={numeric?e=>focusNumericInput(value,onChange?()=>onChange(''):()=>{},e):undefined} onChange={e=>onChange?.(numeric?grouped(e.target.value):e.target.value)}/>}</label>}
const defaults:Record<string,Values>={
 capacity:{income:'60000000',existing:'0',principal:'300000000',rate:'4',years:'30',limit:'40'},
 budget:{income:'3500000',fixed:'1200000',living:'900000',debt:'400000',savings:'10000000',target:'50000000'},
 rentCompare:{jeonseDeposit:'300000000',jeonseLoan:'200000000',jeonseRate:'4',monthlyDeposit:'30000000',rent:'900000',maintenance:'150000',months:'24',opportunity:'3'},
 prepayment:{balance:'200000000',rate:'4',years:'20',repay:'30000000',fee:'1'},
 retirement:{start:'2023-01-01',end:new Date().toISOString().slice(0,10),wage:'3500000',leave:'0'},
 parentalLeave:{wage:'3500000',months:'12',rate:'80',cap:'2500000',floor:'700000',fixed:'1800000'},
 carCost:{price:'40000000',down:'10000000',rate:'5',months:'60',insurance:'1200000',tax:'500000',fuel:'200000',parking:'100000',maintenance:'600000'},
 moving:{brokerage:'1000000',moving:'1500000',repair:'3000000',furniture:'2000000',appliances:'3000000',registration:'1500000',depositGap:'0'}
}
export default function AdvancedCalculator({id,title,restoreInput,onCalculated,member,onNavigate}:Props){
 const [v,setV]=useState<Values>(()=>({...defaults[id]}));const [result,setResult]=useState<CalcResult|null>(null);const [scenarios,setScenarios]=useState<CalcResult[]>([])
 useEffect(()=>{setV({...defaults[id]});setResult(null);setScenarios([])},[id])
 useEffect(()=>{if(restoreInput?._calculatorType===id){const restored=Object.fromEntries(Object.entries(restoreInput).filter(([key])=>!key.startsWith('_')).map(([key,value])=>[key,String(value??'')]));setV({...defaults[id],...restored});setResult(null)}},[restoreInput,id])
 const set=(key:string)=>(value:string)=>setV(old=>({...old,[key]:value}))
 const date=(key:string,label:string)=><Field label={label} type="date" value={v[key]} onChange={set(key)}/>
 const money=(key:string,label:string)=><Field label={label} value={v[key]} onChange={set(key)}/>
 const calculate=()=>{let r:CalcResult|undefined
  if(id==='capacity'){const x=repaymentCapacity(n(v.income),n(v.existing),n(v.principal),n(v.rate),n(v.years)*12,n(v.limit));r={main:`DSR ${num(x.dsr)}%`,lines:[['예상 월 상환액',won(x.payment)],['입력 한도 기준',`${v.limit}%`],['한도 내 추정 원금',won(x.affordablePrincipal)],['판정',x.withinLimit?'입력한 기준 이내':'입력한 기준 초과']],note:'원리금균등상환과 사용자가 입력한 DSR 기준의 단순 추정입니다. 실제 규제·인정소득·스트레스 금리는 금융기관 심사를 따릅니다.',raw:x}}
  if(id==='budget'){const x=monthlyBudget(n(v.income),n(v.fixed),n(v.living),n(v.debt),n(v.savings),n(v.target));r={main:`월 ${won(x.available)} 저축 가능`,lines:[['3개월 비상금',won(x.emergency3)],['6개월 비상금',won(x.emergency6)],['12개월 비상금',won(x.emergency12)],['목표 예상 기간',Number.isFinite(x.targetMonths)?`${x.targetMonths}개월`:'현재 예산으로 달성 어려움']],note:'입력한 월평균 금액이 계속된다는 가정이며 물가, 수익률과 비정기 지출은 포함하지 않습니다.',raw:x}}
  if(id==='rentCompare'){const jeonse=housingRentComparison(n(v.jeonseDeposit),0,n(v.jeonseLoan),n(v.jeonseRate),n(v.maintenance),n(v.months),n(v.opportunity));const monthly=housingRentComparison(n(v.monthlyDeposit),n(v.rent),0,0,n(v.maintenance),n(v.months),n(v.opportunity));const cheaper=jeonse.total<=monthly.total?'전세':'월세';r={main:`${cheaper}가 ${won(Math.abs(jeonse.total-monthly.total))} 적음`,lines:[['전세 총주거비',won(jeonse.total)],['월세 총주거비',won(monthly.total)],['전세 월평균',won(jeonse.monthlyAverage)],['월세 월평균',won(monthly.monthlyAverage)]],note:'보증금 자체는 반환된다고 보고 대출이자와 자기자금 기회비용만 비용으로 반영합니다. 보증 위험과 중개보수는 별도 확인하세요.',raw:{jeonse,monthly}}}
  if(id==='prepayment'){const x=earlyRepayment(n(v.balance),n(v.rate),n(v.years)*12,n(v.repay),n(v.fee));r={main:`순절감 ${won(x.netBenefit)}`,lines:[['예상 이자 절감',won(x.interestSaved)],['중도상환수수료',won(x.fee)],['상환 전 월 납입',won(x.beforePayment)],['상환 후 월 납입',won(x.afterPayment)]],note:'남은 기간과 금리가 유지되고 상환 후 월 납입액을 다시 계산하는 가정입니다. 실제 수수료 면제비율과 상환 방식은 약정을 확인하세요.',raw:x}}
  if(id==='retirement'){const x=retirementEstimate(v.start,v.end,n(v.wage),n(v.leave));r={main:`예상 합계 ${won(x.total)}`,lines:[['계속근로기간',`${Math.floor(x.serviceYears)}년 · ${x.serviceDays}일`],['예상 퇴직금',won(x.retirement)],['미사용 연차수당',won(x.leavePay)],['평균 일급 가정',won(x.dailyWage)]],note:'1년 이상 계속근로와 월 평균임금÷30을 단순 적용한 참고값입니다. 실제 평균임금, 통상임금과 연차 발생·소멸은 근로관계를 확인하세요.',raw:x}}
  if(id==='parentalLeave'){const x=leaveIncome(n(v.wage),n(v.months),n(v.rate),n(v.cap),n(v.floor));const shortage=Math.max(0,n(v.fixed)-x.monthly);r={main:`월 예상 ${won(x.monthly)}`,lines:[['기간 총액',won(x.total)],['기존 급여 대비 감소',won(x.loss)],['월 고정비 부족',won(shortage)],['휴직 기간',`${v.months}개월`]],note:'사용자가 입력한 지급률·상한·하한을 적용한 계획용 계산입니다. 출산휴가·육아휴직 급여의 실제 요건과 최신 금액은 고용24에서 확인하세요.',raw:{...x,shortage}}}
  if(id==='carCost'){const x=carOwnershipCost(n(v.price),n(v.down),n(v.rate),n(v.months),n(v.insurance),n(v.tax),n(v.fuel),n(v.parking),n(v.maintenance));r={main:`월 총비용 ${won(x.monthlyTotal)}`,lines:[['월 할부금',won(x.installment)],['월 유지비',won(x.monthlyOther)],['연간 총비용',won(x.annualTotal)],['총 할부이자',won(x.totalInterest)]],note:'차량 감가상각, 취등록비, 통행료와 돌발 수리비는 포함하지 않은 현금 지출 추정입니다.',raw:x}}
  if(id==='moving'){const x=movingCost(n(v.brokerage),n(v.moving),n(v.repair),n(v.furniture),n(v.appliances),n(v.registration),n(v.depositGap));r={main:`총 준비금 ${won(x.total)}`,lines:[['계약·등기 비용',won(x.brokerage+x.registration)],['이사·수리 비용',won(x.moving+x.repair)],['가구·가전 비용',won(x.furniture+x.appliances)],['보증금 추가분',won(x.depositGap)]],note:'입력한 견적의 합계이며 실제 중개보수 상한, 세금, 일정과 추가 공사비는 계약 전에 확인하세요.',raw:x}}
  if(!r)return;setResult(r);setScenarios(old=>[r,...old].slice(0,3));onCalculated(title,v,r)
 }
 const fields=useMemo(()=>{switch(id){
  case'capacity':return <>{money('income','연 소득')}{money('existing','기존 대출 연간 원리금')}<Field label="신규 대출 원금" value={v.principal} onChange={set('principal')}/><Field label="연 이자율(%)" value={v.rate} onChange={set('rate')}/><Field label="기간(년)" value={v.years} onChange={set('years')}/><Field label="비교 DSR 기준(%)" value={v.limit} onChange={set('limit')}/></>
  case'budget':return <>{money('income','월 실수령액')}{money('fixed','월 고정비')}{money('living','월 생활비')}{money('debt','월 대출 상환')}{money('savings','현재 저축액')}{money('target','저축 목표액')}</>
  case'rentCompare':return <>{money('jeonseDeposit','전세 보증금')}{money('jeonseLoan','전세대출금')}<Field label="전세대출 연이율(%)" value={v.jeonseRate} onChange={set('jeonseRate')}/>{money('monthlyDeposit','월세 보증금')}{money('rent','월세')}{money('maintenance','공통 월 관리비')}<Field label="거주 기간(개월)" value={v.months} onChange={set('months')}/><Field label="자기자금 기회비용률(%)" value={v.opportunity} onChange={set('opportunity')}/></>
  case'prepayment':return <>{money('balance','현재 대출 잔액')}<Field label="연 이자율(%)" value={v.rate} onChange={set('rate')}/><Field label="남은 기간(년)" value={v.years} onChange={set('years')}/>{money('repay','중도상환 금액')}<Field label="중도상환수수료율(%)" value={v.fee} onChange={set('fee')}/></>
  case'retirement':return <>{date('start','입사일')}{date('end','퇴사 예정일')}{money('wage','최근 3개월 월평균 임금')}<Field label="미사용 연차(일)" value={v.leave} onChange={set('leave')}/></>
  case'parentalLeave':return <>{money('wage','휴직 전 월급')}<Field label="휴직 기간(개월)" value={v.months} onChange={set('months')}/><Field label="지급률(%)" value={v.rate} onChange={set('rate')}/>{money('cap','월 상한액')}{money('floor','월 하한액')}{money('fixed','가구 월 고정비')}</>
  case'carCost':return <>{money('price','차량 가격')}{money('down','선수금')}<Field label="할부 연이율(%)" value={v.rate} onChange={set('rate')}/><Field label="할부 기간(개월)" value={v.months} onChange={set('months')}/>{money('insurance','연 보험료')}{money('tax','연 자동차세')}{money('fuel','월 연료·충전비')}{money('parking','월 주차비')}{money('maintenance','연 정비비')}</>
  default:return <>{money('brokerage','중개보수')}{money('moving','이사비')}{money('repair','수리·청소비')}{money('furniture','가구비')}{money('appliances','가전비')}{money('registration','세금·등기·법무비')}{money('depositGap','보증금 추가 필요액')}</>
 }},[id,v])
 return <>{<div className="form-grid">{fields}<button className="primary" onClick={calculate}>계산하기</button></div>}{result&&<section className="result" aria-live="polite"><small>계산 결과</small><strong>{result.main}</strong>{result.lines.map(([a,b])=><div className="result-row" key={a}><span>{a}</span><b>{b}</b></div>)}<p>{result.note}</p></section>}{member&&scenarios.length>1&&<section className="scenario-compare"><small>SCENARIO COMPARISON</small><h3>최근 조건 비교</h3>{scenarios.map((scenario,index)=><div key={index}><span>시나리오 {scenarios.length-index}</span><b>{scenario.main}</b></div>)}</section>}<div className="standard-note"><b>기준과 가정</b><span>2026년 8월 최종 검토 · 표시 금액은 원 단위 반올림 · 입력 조건이 유지된다는 계획용 추정</span></div>{id==='budget'&&result&&<button className="linked-action" onClick={()=>onNavigate?.('saving',{a:v.target,b:v.savings,c:String(result.raw.available||0)})}>이 결과로 목표 저축 기간 자세히 계산 →</button>}{id==='capacity'&&result&&<button className="linked-action" onClick={()=>onNavigate?.('loan',{a:v.principal,b:v.rate,c:String(n(v.years)*12),mode:'annuity'})}>이 대출 조건으로 상환표 계산 →</button>}</>
}
