import {useEffect,useMemo,useState} from 'react'

type Props={onCalculated:(title:string,input:unknown,result:unknown)=>void;restoreInput?:Record<string,unknown>|null}
type PaymentKind='contract'|'interim'
type Payment={id:string;kind:PaymentKind;month:string;amount:string;memo:string}
type PurchaseResult={required:number;closing:number;minimum:number;firstShortage?:string;planned:number;initialCash:number;contract:number;interimTotal:number;balance:number;sources:number;mortgage:number;deposit:number;saleProceeds:number;otherSource:number;cashCosts:number;brokerage:number;tax:number;legal:number;moving:number;payTaxByCard:boolean;rows:{month:string;closing:number;memo:string}[]}
const now=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const plus=(base:string,n:number)=>{const [y,m]=base.split('-').map(Number),d=new Date(y,m-1+n,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const valid=(v:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(v)
const raw=(v:string)=>Number(v.replaceAll(',',''))||0
const won=(v:string)=>raw(v)*10000
const fromWon=(v:unknown)=>String(Math.round(Number(v||0)/10000))
const format=(v:string)=>{const x=v.replaceAll(',','').replace(/[^0-9.-]/g,'');if(!x)return '';return x.replace(/\B(?=(\d{3})+(?!\d))/g,',')}
const show=(v:number)=>`${Math.round(v/10000).toLocaleString()}만원`
const Month=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="field"><span>{label}</span><input maxLength={7} value={value} placeholder="YYYY-MM" onChange={e=>set(e.target.value.replace(/[^0-9-]/g,''))}/></label>
const Money=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="field"><span>{label}</span><span className="input-unit"><input inputMode="numeric" value={format(value)} onChange={e=>set(format(e.target.value))}/><em>만원</em></span></label>

export default function ApartmentPurchaseCalculator({onCalculated,restoreInput}:Props){
 const base=now()
 const [startMonth,setStartMonth]=useState(base),[closingMonth,setClosingMonth]=useState(plus(base,3))
 const [initialCash,setInitialCash]=useState(''),[price,setPrice]=useState('')
 const [mortgage,setMortgage]=useState(''),[deposit,setDeposit]=useState(''),[saleProceeds,setSaleProceeds]=useState(''),[otherSource,setOtherSource]=useState('')
 const [brokerage,setBrokerage]=useState(''),[tax,setTax]=useState(''),[legal,setLegal]=useState(''),[moving,setMoving]=useState(''),[payTaxByCard,setPayTaxByCard]=useState(false)
 const [payments,setPayments]=useState<Payment[]>([]),[result,setResult]=useState<PurchaseResult|null>(null),[error,setError]=useState('')
 useEffect(()=>{if(!restoreInput)return;const m=(k:string,s:(v:string)=>void)=>s(fromWon(restoreInput[k]));setStartMonth(String(restoreInput.startMonth||base));setClosingMonth(String(restoreInput.closingMonth||plus(base,3)));m('initialCash',setInitialCash);m('price',setPrice);m('mortgage',setMortgage);m('deposit',setDeposit);m('saleProceeds',setSaleProceeds);m('otherSource',setOtherSource);m('brokerage',setBrokerage);m('tax',setTax);m('legal',setLegal);m('moving',setMoving);setPayTaxByCard(Boolean(restoreInput.payTaxByCard));const old=Array.isArray(restoreInput.payments)?restoreInput.payments as {kind?:PaymentKind;month:string;amount:number;memo:string}[]:[];const restored=old.map(x=>({id:crypto.randomUUID(),kind:x.kind==='contract'?'contract' as const:'interim' as const,month:x.month,amount:fromWon(x.amount),memo:x.memo||''}));const legacyContract=Number(restoreInput.contract||0);if(legacyContract>0&&!restored.some(x=>x.kind==='contract'))restored.unshift({id:crypto.randomUUID(),kind:'contract',month:String(restoreInput.startMonth||base),amount:fromWon(legacyContract),memo:''});setPayments(restored);setResult(null)},[restoreInput])
 const add=(kind:PaymentKind)=>setPayments(v=>[...v,{id:crypto.randomUUID(),kind,month:kind==='contract'?startMonth:plus(startMonth,1),amount:'',memo:''}])
 const update=(id:string,key:keyof Omit<Payment,'id'>,value:string)=>setPayments(v=>v.map(x=>x.id!==id?x:key==='kind'?{...x,kind:value as PaymentKind}:{...x,[key]:value}))
 const calculate=()=>{try{
  if(!valid(startMonth)||!valid(closingMonth)||startMonth>closingMonth)throw new Error('계산 시작월과 잔금월을 올바르게 입력해 주세요.')
  if(won(price)<=0)throw new Error('0보다 큰 매매가격을 입력해 주세요.')
  const normalized=payments.filter(x=>x.amount||x.memo).map((x,i)=>{if(!valid(x.month)||x.month<startMonth||x.month>closingMonth)throw new Error(`${i+1}번째 납부월은 계산 기간 안이어야 합니다.`);return {kind:x.kind,month:x.month,amount:won(x.amount),memo:x.memo.slice(0,60)}}).sort((a,b)=>a.month.localeCompare(b.month))
  const contractTotal=normalized.filter(x=>x.kind==='contract').reduce((s,x)=>s+x.amount,0),interimTotal=normalized.filter(x=>x.kind==='interim').reduce((s,x)=>s+x.amount,0)
  const input={planType:'purchase',startMonth,closingMonth,initialCash:won(initialCash),price:won(price),contract:contractTotal,mortgage:won(mortgage),deposit:won(deposit),saleProceeds:won(saleProceeds),otherSource:won(otherSource),brokerage:won(brokerage),tax:won(tax),legal:won(legal),moving:won(moving),payTaxByCard,payments:normalized}
  const events=new Map<string,{amount:number;memo:string[]}>(),put=(month:string,amount:number,memo:string)=>{const e=events.get(month)||{amount:0,memo:[]};e.amount+=amount;if(memo)e.memo.push(memo);events.set(month,e)}
  let contractRound=0,interimRound=0;normalized.forEach(x=>{const round=x.kind==='contract'?++contractRound:++interimRound;put(x.month,-x.amount,x.memo||`${x.kind==='contract'?'계약금':'중도금'} ${round}회`)})
  const balance=Math.max(0,input.price-contractTotal-interimTotal);put(closingMonth,input.mortgage+input.deposit+input.saleProceeds+input.otherSource-balance-input.brokerage-(payTaxByCard?0:input.tax)-input.legal-input.moving,payTaxByCard?'잔금 · 주담대 · 취득세 카드':'잔금 정산')
  const rows=[];let cash=input.initialCash,minimum=cash,firstShortage:string|undefined;for(let month=startMonth;month<=closingMonth;month=plus(month,1)){const e=events.get(month);cash+=e?.amount||0;if(cash<minimum)minimum=cash;if(cash<0&&!firstShortage)firstShortage=month;rows.push({month,closing:cash,memo:e?.memo.join(' · ')||''})}
  const sources=input.mortgage+input.deposit+input.saleProceeds+input.otherSource,cashCosts=input.brokerage+(payTaxByCard?0:input.tax)+input.legal+input.moving
  const required=Math.max(0,-cash),planned=contractTotal+interimTotal+balance+input.brokerage+input.tax+input.legal+input.moving
  const next={required,closing:cash,minimum,firstShortage,planned,initialCash:input.initialCash,contract:contractTotal,interimTotal,balance,sources,mortgage:input.mortgage,deposit:input.deposit,saleProceeds:input.saleProceeds,otherSource:input.otherSource,cashCosts,brokerage:input.brokerage,tax:input.tax,legal:input.legal,moving:input.moving,payTaxByCard,rows};setResult(next);setError('');onCalculated('아파트 매매 자금 계획',input,{...next,main:`잔금 시 부족자금 ${show(required)}`})
 }catch(e){setResult(null);setError(e instanceof Error?e.message:'입력값을 확인해 주세요.')}}
 const reset=()=>{setStartMonth(base);setClosingMonth(plus(base,3));[setInitialCash,setPrice,setMortgage,setDeposit,setSaleProceeds,setOtherSource,setBrokerage,setTax,setLegal,setMoving].forEach(s=>s(''));setPayTaxByCard(false);setPayments([]);setResult(null);setError('')}
 const balance=useMemo(()=>Math.max(0,won(price)-payments.reduce((s,x)=>s+won(x.amount),0)),[price,payments])
 return <div className="housing-planner purchase-planner"><div className="planner-intro"><b>계약일부터 잔금일까지 필요한 현금을 확인하세요.</b><p>주택담보대출과 회수 자금은 잔금월 유입으로 계산합니다.</p></div>
  <fieldset><legend>일정·매매대금</legend><div className="form-grid compact"><Month label="계산 시작월" value={startMonth} set={setStartMonth}/><Month label="잔금 예정월" value={closingMonth} set={setClosingMonth}/><Money label="보유 현금" value={initialCash} set={setInitialCash}/><Money label="매매가격" value={price} set={setPrice}/></div><div className="purchase-balance">납부 일정을 제외한 자동 계산 잔금 <b>{show(balance)}</b></div></fieldset>
  <fieldset><legend>계약금·중도금 납부 일정</legend><div className="payment-add-actions"><button className="small-add" onClick={()=>add('contract')}>+ 계약금 추가</button><button className="small-add" onClick={()=>add('interim')}>+ 중도금 추가</button></div>{payments.length===0&&<p className="payment-empty">계약금 또는 중도금을 추가하면 매매가격에서 차감해 잔금을 자동 계산합니다.</p>}{payments.map((x,i)=><div className="purchase-payment" key={x.id}><label className="field"><span>구분</span><select value={x.kind} onChange={e=>update(x.id,'kind',e.target.value as PaymentKind)}><option value="contract">계약금</option><option value="interim">중도금</option></select></label><Month label={`${i+1}회차 납부월`} value={x.month} set={v=>update(x.id,'month',v)}/><Money label="납부액" value={x.amount} set={v=>update(x.id,'amount',v)}/><label className="field"><span>메모</span><input maxLength={60} value={x.memo} placeholder="선택 입력" onChange={e=>update(x.id,'memo',e.target.value)}/></label><button aria-label={`${i+1}회차 삭제`} onClick={()=>setPayments(v=>v.filter(p=>p.id!==x.id))}>삭제</button></div>)}</fieldset>
  <fieldset><legend>매매 자금 마련</legend><div className="form-grid compact"><Money label="주택담보대출 실행액" value={mortgage} set={setMortgage}/><Money label="전세보증금 회수" value={deposit} set={setDeposit}/><Money label="기존 주택 매각대금" value={saleProceeds} set={setSaleProceeds}/><Money label="기타 자금" value={otherSource} set={setOtherSource}/></div></fieldset>
  <fieldset><legend>거래 부대비용</legend><div className="form-grid compact"><Money label="중개보수" value={brokerage} set={setBrokerage}/><div className="saving-field"><Money label="예상 취득 관련 세금" value={tax} set={setTax}/><label className="saving-start-toggle"><input type="checkbox" checked={payTaxByCard} onChange={e=>setPayTaxByCard(e.target.checked)}/><span>카드 결제 (현금 차감 제외)</span></label></div><Money label="법무·등기·채권 비용" value={legal} set={setLegal}/><Money label="이사·수리비" value={moving} set={setMoving}/></div></fieldset>
  <button className="planner-reset" onClick={reset}>초기화</button><button className="primary planner-submit" onClick={calculate}>매매 자금 계산하기</button>{error&&<p className="planner-error">{error}</p>}
  {result&&<><section className="planner-summary"><div><small>잔금 시 부족자금</small><strong>{show(result.required)}</strong><p>{result.firstShortage?`${result.firstShortage}부터 보유 현금보다 납부액이 큽니다.`:'계약부터 잔금까지 필요한 현금이 마련되어 있습니다.'}</p></div><dl aria-label="핵심 자금 지표"><div><dt>계약금·중도금 합계</dt><dd>{show(result.contract+result.interimTotal)}</dd></div><div><dt>자동 계산 잔금</dt><dd>{show(result.balance)}</dd></div><div><dt>잔금 후 남은 현금</dt><dd>{show(result.closing)}</dd></div><div><dt>총 예상 소요비용</dt><dd>{show(result.planned)}</dd></div></dl></section><section className="final-breakdown purchase-breakdown"><div className="final-breakdown-head"><div><small>CLOSING BREAKDOWN</small><h3>잔금 정산 계산 내역</h3></div><strong className={result.closing<0?'shortage':''}>{show(result.closing)}</strong></div><div className="horizontal-scroll-hint final-scroll-hint" aria-hidden="true">← 좌우로 밀어 전체 계산식 보기 →</div><div className="final-equation"><span>{show(result.initialCash)}<small>보유 현금</small></span><i>+</i><span>{show(result.sources)}<small>마련한 자금</small></span><i>−</i><span>{show(result.contract+result.interimTotal+result.balance)}<small>매매대금</small></span><i>−</i><span>{show(result.cashCosts)}<small>현금 부대비용</small></span><i>=</i><span className={result.closing<0?'shortage':''}>{show(result.closing)}<small>남은 현금</small></span></div><div className="breakdown-list-title"><b>↓ 매매대금·자금 마련 구성</b><span>계약부터 잔금일까지 반영된 항목입니다.</span></div><dl><div><dt>계약금 합계</dt><dd>− {show(result.contract)}</dd></div><div><dt>주택담보대출</dt><dd>+ {show(result.mortgage)}</dd></div><div><dt>중도금 합계</dt><dd>− {show(result.interimTotal)}</dd></div><div><dt>전세보증금 회수</dt><dd>+ {show(result.deposit)}</dd></div><div><dt>잔금</dt><dd>− {show(result.balance)}</dd></div><div><dt>기존 주택 매각대금</dt><dd>+ {show(result.saleProceeds)}</dd></div><div><dt>기타 자금</dt><dd>+ {show(result.otherSource)}</dd></div></dl><div className="breakdown-list-title purchase-cost-title"><b>↓ 거래 부대비용 구성</b><span>카드 결제 취득세는 현금 계산에서 제외됩니다.</span></div><dl><div><dt>중개보수</dt><dd>− {show(result.brokerage)}</dd></div><div className={result.payTaxByCard?'excluded':''}><dt>예상 취득 관련 세금</dt><dd>{result.payTaxByCard?`${show(result.tax)} · 카드 결제 제외`:`− ${show(result.tax)}`}</dd></div><div><dt>법무·등기·채권 비용</dt><dd>− {show(result.legal)}</dd></div><div><dt>이사·수리비</dt><dd>− {show(result.moving)}</dd></div></dl><div className="breakdown-total"><span>현금 부대비용 합계</span><strong>{show(result.cashCosts)}</strong></div><p>부족자금은 위 계산 결과인 남은 현금이 음수일 때 그 절댓값으로 표시합니다. 실제 대출 가능액이나 확정 세금이 아니므로 계약 및 금융기관 조건을 함께 확인하세요.</p></section><div className="table-wrap"><table><thead><tr><th>기간</th><th>남은 현금</th><th>반영 내용</th></tr></thead><tbody>{result.rows.map(x=><tr key={x.month}><td>{x.month}</td><td className={x.closing<0?'shortage':''}>{show(x.closing)}</td><td>{x.memo||'—'}</td></tr>)}</tbody></table></div></>}
 </div>
}
