export type Member={id:number;email:string}
export type History={id:number;calculatorType:string;title:string;inputJson:string;resultJson:string;createdAt:string}
export type SaveHistory={calculatorType:string;title:string;inputJson:string;resultJson:string}
export type PublicShare=SaveHistory&{shareToken:string;createdAt:string}
export type PriceItem={itemCode:string;name:string;unit:string;quantity:number;currentPrice:number;dayAgoPrice:number|null;weekAgoPrice:number|null;monthAgoPrice:number|null;yearAgoPrice:number|null}
export type PriceDashboard={asOfDate:string;source:string;demo:boolean;items:PriceItem[]}
export type PublicPriceRow={date:string;marketType:string;categoryCode:string;categoryName:string;itemCode:string;itemName:string;varietyCode:string;varietyName:string;gradeCode:string;gradeName:string;regionCode:string;regionName:string;marketCode:string;marketName:string;unit:string;price:number|null;normalizedPrice:number|null;minPrice:number|null;averagePrice:number|null;maxPrice:number|null}
export type PublicPriceResult={from:string;to:string;totalCount:number;items:PublicPriceRow[];source:string}
export type PublicPriceItemOption={itemCode:string;itemName:string}
export type PublicPriceStatisticsPoint={label:string;code:string;minPrice:number;averagePrice:number;maxPrice:number;sampleCount:number}
export type PublicPriceStatistics={kind:'period'|'regional';from:string;to:string;itemCode:string;itemName:string;totalSamples:number;points:PublicPriceStatisticsPoint[]}
export type SchoolInfo={educationOfficeCode:string;schoolCode:string;educationOfficeName:string;schoolName:string;schoolKind:string;locationName:string;address:string;coeducationType:string;foundationType?:string;status?:string;openedOn?:string;homepageUrl:string}
export type EducationSummary={asOfDate:string|null;regions:{region:string;schoolKind:string;schoolCount:number}[]}
export type EducationDailySummary={date:string;mealCount:number;mealSchoolCount:number;upcomingScheduleCount:number;mealTypes:{label:string;value:number}[];batch:{nextSchoolOffset:number;completedCycles:number;lastStartedAt:string|null;lastFinishedAt:string|null;lastStatus:string};totalSchools:number;freshSchools:number;failedSchools:number;mealStatistics:{mealSamples:number;calorieSamples:number;averageCalories:number|null;topMenus:{menu:string;count:number}[];allergyMeals:Record<string,number>};events:{date:string;name:string;schoolCount:number}[]}
export type EducationDisclosureSummary={year:number;metrics:{region:string;metric:string;value:number;schoolCount:number}[];batch:{nextIndex:number;completedCycles:number;lastStartedAt:string|null;lastFinishedAt:string|null;lastStatus:string};totalScopes:number}
export type EducationSchoolDetail={school:SchoolInfo;metrics:{year:number;metric:string;value:number}[];meals:{date:string;name:string;menu:string;calorie:string}[];schedules:{date:string;name:string;content:string;gradeScope:string}[]}
export type EducationTrends={year:number;annual:{year:number;students:number;studentSchools:number;classes:number;classSchools:number;teachers:number;teacherSchools:number}[];changes:{region:string;matchedSchools:number;previousStudents:number;currentStudents:number}[]}
export type EducationRatio={region:string;denominatorMetric:string;numerator:number;denominator:number;schools:number}
export type EducationDisclosurePage={page:number;pageSize:number;total:number;items:{type:string;year:number;school:string;name:string;region:string;payload:string;collectedAt:string}[]}
let csrf=''
async function token(){if(csrf)return csrf;const r=await fetch('/api/csrf',{credentials:'include'});if(!r.ok)throw new Error('로그인이 필요합니다.');csrf=(await r.json()).token;return csrf}
async function req<T>(path:string,init?:RequestInit){const method=(init?.method||'GET').toUpperCase();const r=await fetch('/api'+path,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(['POST','DELETE'].includes(method)?{'X-XSRF-TOKEN':await token()}:{}),...init?.headers}});if(!r.ok){let message='요청을 처리하지 못했습니다.';try{const body=await r.json() as {detail?:string;message?:string};message=body.detail||body.message||message}catch{/* Empty and non-JSON errors use the safe fallback. */}throw new Error(message)}return r.status===204?undefined as T:r.json() as Promise<T>}
async function priceReq(path:string){try{return await req<PublicPriceResult>(path)}catch(first){await new Promise(resolve=>setTimeout(resolve,500));try{return await req<PublicPriceResult>(path)}catch{throw first}}}
export const educationApi={trends:(year:number,region:string,kind:string)=>req<EducationTrends>(`/public/education/trends?${new URLSearchParams({year:String(year),region,kind})}`),ratios:(year:number)=>req<EducationRatio[]>(`/public/education/ratios?year=${year}`),disclosureTypes:()=>req<string[]>('/public/education/disclosure-types'),disclosures:(filters:{year:number;type:string;region:string;name:string;page:number})=>req<EducationDisclosurePage>(`/public/education/disclosures?${new URLSearchParams(Object.entries(filters).map(([key,value])=>[key,String(value)]))}`),schoolSearch:(name:string)=>req<SchoolInfo[]>(`/public/education/schools?name=${encodeURIComponent(name)}`),schoolDetail:(office:string,school:string)=>req<EducationSchoolDetail>(`/public/education/schools/${encodeURIComponent(office)}/${encodeURIComponent(school)}`),summary:()=>req<EducationSummary>('/public/education/summary'),dailySummary:()=>req<EducationDailySummary>('/public/education/daily-summary'),disclosureSummary:(year:number)=>req<EducationDisclosureSummary>(`/public/education/disclosure-summary?year=${year}`)}
export const api={me:()=>req<Member>('/me'),histories:()=>req<History[]>('/histories'),save:(body:SaveHistory)=>req<History>('/histories',{method:'POST',body:JSON.stringify(body)}),importHistories:(histories:SaveHistory[])=>req<History[]>('/histories/import',{method:'POST',body:JSON.stringify({histories})}),remove:(id:number)=>req<void>(`/histories/${id}`,{method:'DELETE'}),createShare:(body:SaveHistory)=>req<{token:string}>('/shares',{method:'POST',body:JSON.stringify(body)}),publicShare:(token:string)=>req<PublicShare>(`/public/shares/${encodeURIComponent(token)}`),priceDashboard:()=>req<PriceDashboard>('/public/prices/dashboard'),periodRetailPriceItems:()=>req<PublicPriceItemOption[]>('/public/price-lookup/period-retail/items'),regionalPriceItems:()=>req<PublicPriceItemOption[]>('/public/price-lookup/regional/items'),periodRetailStatistics:(from:string,to:string,itemCode:string)=>req<PublicPriceStatistics>(`/public/price-lookup/period-retail/statistics?from=${from}&to=${to}&itemCode=${encodeURIComponent(itemCode)}`),regionalStatistics:(from:string,to:string,itemCode:string)=>req<PublicPriceStatistics>(`/public/price-lookup/regional/statistics?from=${from}&to=${to}&itemCode=${encodeURIComponent(itemCode)}`),periodRetailPrices:(from:string,to:string,itemCode:string)=>priceReq(`/public/price-lookup/period-retail?from=${from}&to=${to}&itemCode=${encodeURIComponent(itemCode)}`),regionalPrices:(from:string,to:string,regionCode:string,itemCode:string)=>priceReq(`/public/price-lookup/regional?from=${from}&to=${to}&regionCode=${encodeURIComponent(regionCode)}&itemCode=${encodeURIComponent(itemCode)}`)}
