import {useEffect,useMemo,useState,type MouseEvent,type ReactNode} from 'react'
import {addDays,dateAtNoon,diffDays,fullAge,loan,LoanMethod,minimumWages,num,pensionCaps,salaryEstimate,salaryRateInfo,splitExpense,won} from './calculations'
import {guides} from './guides'
import {api,History,Member,type SaveHistory} from './api'
import {addLocalHistory,clearLocalHistories,loadLocalHistories,removeLocalHistory,type LocalHistory} from './history'

type Tool={id:string;icon:string;title:string;desc:string;group:string}
const tools:Tool[]=[
 ['date','▦','날짜 차이','두 날짜 사이의 정확한 일수','날짜·시간'],['age','◴','만 나이','기준일의 국제식 만 나이','날짜·시간'],['dday','D','디데이','목표일까지 남은 날짜','날짜·시간'],['percent','%','퍼센트·할인율','증감률과 할인 가격','생활'],['unit','↔','단위 변환','평수·길이·무게 변환','생활'],['ratio','▣','비율·해상도','화면 비율과 새 크기','생활'],['text','Aa','글자·문장 수','공백 포함 글자와 문장','생활'],['random','⚄','랜덤 추첨·팀','공정한 셔플과 팀 나누기','생활'],['timezone','◷','시간대 변환','세계 주요 도시 시간','날짜·시간'],['travel','₩','여행 경비','균등·가중 비용 분담','돈'],['fuel','⛽','연료비·주행비','연비와 거리로 비용 계산','돈'],['saving','◎','목표 저축 기간','목표액까지 필요한 기간','돈'],['study','▤','공부·독서 진도','남은 분량과 일일 목표','성장'],['schedule','✓','일정 계산','반복 일정의 종료일','날짜·시간'],['loan','🏠','대출 계산기','상환 방식별 원금과 이자','돈'],['salary','▥','연봉 계산기','월 실수령액 예상','돈'],['minimum','₩','연도별 최저시급','2011년부터 공식 이력','자료'],['salaryTable','급','연봉 실수령액표','연봉별 월 예상액 비교','자료']
].map(([id,icon,title,desc,group])=>({id,icon,title,desc,group}))
const calculatorTools=tools.filter(x=>!['salary','minimum','salaryTable'].includes(x.id))
const today=new Date().toISOString().slice(0,10)
const n=(v:string)=>Number(v.replaceAll(',',''))||0
const groupedNumber=(value:string|number)=>{
 const raw=String(value).replaceAll(',','').replace(/[^0-9.-]/g,'')
 if(!raw)return ''
 const negative=raw.startsWith('-')?'-':''
 const unsigned=raw.replace('-','')
 const [integer,decimal]=unsigned.split('.')
 const grouped=(integer||'0').replace(/\B(?=(\d{3})+(?!\d))/g,',')
 return negative+grouped+(unsigned.includes('.')?'.'+(decimal??''):'')
}

function Field({label,value,onChange,type='number',step,children}:{label:string,value?:string|number,onChange?:(v:string)=>void,type?:string,step?:string,children?:ReactNode}){
 const numeric=type==='number'
 return <label className="field"><span>{label}</span>{children||<input type={numeric?'text':type} inputMode={numeric?'decimal':undefined} step={step} value={numeric?groupedNumber(value??''):value} onChange={e=>onChange?.(numeric?groupedNumber(e.target.value):e.target.value)}/>}</label>
}
function Select({label,value,onChange,options}:{label:string,value:string,onChange:(v:string)=>void,options:[string,string][]}){const visibleOptions=label==='적용 연도'?[...options,['2022','2022'],['2021','2021'],['2020','2020']] as [string,string][]:options;return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}>{visibleOptions.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></Field>}
function Result({main,lines=[],note}:{main:string,lines?:[string,string][],note?:string}){return <section className="result" aria-live="polite"><small>계산 결과</small><strong>{main}</strong>{lines.map(([a,b])=><div className="result-row" key={a}><span>{a}</span><b>{b}</b></div>)}{note&&<p>{note}</p>}</section>}

function Calculator({id,onCalculated}:{id:string,onCalculated:(title:string,input:unknown,result:unknown)=>void}){
 const [a,setA]=useState(id==='date'?today:'');const [b,setB]=useState(id==='date'?today:'');const [c,setC]=useState('');const [mode,setMode]=useState('');const [result,setResult]=useState<{main:string;lines?:[string,string][];note?:string;raw?:unknown}|null>(null)
 useEffect(()=>{setA(id==='date'?today:'');setB(id==='date'?today:'');setC('');setMode('');setResult(null)},[id])
 const done=(r:{main:string;lines?:[string,string][];note?:string;raw?:unknown})=>{setResult(r);onCalculated(tools.find(x=>x.id===id)!.title,{a,b,c,mode},r)}
 if(id==='minimum')return <Minimum/>
 if(id==='salaryTable')return <SalaryTable/>
 const calculate=()=>{
  const empty=(value:string)=>!value.trim()
  let warning=''
  if(id==='date'&&(empty(a)||empty(b)))warning='시작일과 종료일을 모두 선택해 주세요.'
  else if(id==='age'&&empty(a))warning='생년월일을 선택해 주세요.'
  else if(id==='dday'&&empty(a))warning='목표일을 선택해 주세요.'
  else if(id==='percent'&&(empty(a)||empty(b)))warning='계산할 두 값을 모두 입력해 주세요.'
  else if(id==='unit'&&empty(a))warning='변환할 값을 입력해 주세요.'
  else if(id==='ratio'&&(n(a)<=0||n(b)<=0||n(c)<=0))warning='너비와 높이는 0보다 큰 값으로 입력해 주세요.'
  else if(id==='random'&&!a.split(/[,\n]/).some(x=>x.trim()))warning='추첨하거나 나눌 항목을 입력해 주세요.'
  else if(id==='travel'&&(empty(a)||n(b)<=0))warning='총 경비와 1명 이상의 인원을 입력해 주세요.'
  else if(id==='fuel'&&(empty(a)||n(b)<=0||empty(c)))warning='거리, 0보다 큰 연비와 유가를 입력해 주세요.'
  else if(id==='saving'&&(empty(a)||empty(b)||n(c)<=0))warning='목표액, 현재 금액과 0보다 큰 월 저축액을 입력해 주세요.'
  else if(id==='study'&&(n(a)<=0||empty(b)||n(c)<=0))warning='전체 분량, 완료 분량과 0보다 큰 남은 일수를 입력해 주세요.'
  else if(id==='schedule'&&(empty(a)||n(b)<=0||n(c)<=0))warning='첫 일정, 횟수와 0보다 큰 간격을 입력해 주세요.'
  else if(id==='loan'&&(n(a)<=0||n(b)<0||n(c)<=0||empty(b)))warning='대출 원금, 0 이상의 이자율과 0보다 큰 기간을 입력해 주세요.'
  else if(id==='salary'&&n(a)<=0)warning='0보다 큰 연봉을 입력해 주세요.'
  if(warning){setResult({main:'입력값을 확인해 주세요',note:warning});return}
  if(id==='date'){const d=diffDays(a,b);done({main:`${Math.abs(d).toLocaleString()}일`,lines:[['방향',d===0?'같은 날':d>0?'종료일이 이후':'종료일이 이전'],['양 끝 날짜 포함',`${Math.abs(d)+1}일`]]})}
  else if(id==='age'){const base=b||today;const age=fullAge(a,base);done({main:`만 ${age}세`,lines:[['기준일',base],['한국식 연 나이',`${dateAtNoon(base).getFullYear()-dateAtNoon(a).getFullYear()}세`]]})}
  else if(id==='dday'){const d=diffDays(today,a);done({main:d===0?'D-DAY':d>0?`D-${d}`:`D+${Math.abs(d)}`,lines:[['오늘',today],['목표일',a]]})}
  else if(id==='percent'){const base=n(a),value=n(b);if(mode==='discount'){const price=base*(1-value/100);done({main:won(price),lines:[['할인 금액',won(base-price)],['할인율',`${num(value)}%`]]})}else{const pct=base===0?0:(value-base)/Math.abs(base)*100;done({main:`${pct>=0?'+':''}${num(pct)}%`,lines:[['차이',num(value-base)],['기준값',num(base)]]})}}
  else if(id==='unit'){const value=n(a);const factors:Record<string,[number,string]>= {pyeong:[3.305785,'㎡'],meter:[100,'cm'],km:[1000,'m'],kg:[1000,'g'],lb:[0.45359237,'kg']};const [f,u]=factors[mode||'pyeong'];done({main:`${num(value*f,6)} ${u}`})}
  else if(id==='ratio'){const w=n(a),h=n(b),newW=n(c);const g=(x:number,y:number):number=>y?g(y,x%y):x;const q=g(w,h);done({main:`${w/q}:${h/q}`,lines:[['새 너비',`${num(newW,0)} px`],['새 높이',`${num(newW*h/w,0)} px`]]})}
  else if(id==='text'){const text=a;done({main:`${[...text].length.toLocaleString()}자`,lines:[['공백 제외',[...text.replace(/\s/g,'')].length.toLocaleString()],['단어',text.trim()?text.trim().split(/\s+/).length.toLocaleString():'0'],['문장',(text.match(/[.!?。！？]+/g)||[]).length.toLocaleString()],['줄',text?text.split(/\r?\n/).length.toLocaleString():'0']]})}
  else if(id==='random'){const items=a.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}const teams=Math.max(1,n(b)||1);done({main:mode==='pick'?(items[0]||'항목을 입력하세요'):`${teams}개 팀`,lines:mode==='pick'?[]:Array.from({length:teams},(_,i)=>[`팀 ${i+1}`,items.filter((_,j)=>j%teams===i).join(', ')])})}
  else if(id==='timezone'){const date=a?new Date(a):new Date();const zone=mode||'Asia/Seoul';done({main:new Intl.DateTimeFormat('ko-KR',{dateStyle:'full',timeStyle:'short',timeZone:zone}).format(date),lines:[['시간대',zone]],note:'입력 시각은 현재 기기의 현지 시간으로 해석합니다.'})}
  else if(id==='travel'){const total=n(a),people=Math.max(1,n(b)),weights=c.split(',').map(n);const shares=mode==='weighted'?splitExpense(total,people,weights.length?weights:Array(people).fill(1)):Array(people).fill(total/people);done({main:`1인 평균 ${won(total/people)}`,lines:shares.map((x,i)=>[`${i+1}번`,won(x)])})}
  else if(id==='fuel'){const distance=n(a),eff=n(b),price=n(c),cost=eff?distance/eff*price:0;done({main:won(cost),lines:[['필요 연료',`${num(eff?distance/eff:0)} L`],['1km당',won(distance?cost/distance:0)]]})}
  else if(id==='saving'){const goal=n(a),current=n(b),monthly=n(c),months=monthly>0?Math.max(0,Math.ceil((goal-current)/monthly)):0;done({main:`${months}개월`,lines:[['예상 달성일',addDays(today,Math.round(months*30.436875))],['남은 금액',won(Math.max(0,goal-current))]]})}
  else if(id==='study'){const total=n(a),doneValue=n(b),days=Math.max(1,n(c));done({main:`하루 ${num(Math.max(0,total-doneValue)/days)} ${mode||'쪽'}`,lines:[['현재 진도',`${num(total?doneValue/total*100:0)}%`],['남은 분량',num(Math.max(0,total-doneValue))]]})}
  else if(id==='schedule'){const count=Math.max(1,n(b)),interval=Math.max(1,n(c));done({main:addDays(a,(count-1)*interval),lines:[['첫 일정',a],['총 횟수',`${count}회`],['간격',`${interval}일`]]})}
  else if(id==='loan'){const x=loan(n(a),n(b),Math.max(1,n(c)),(mode||'annuity') as LoanMethod);done({main:`월 ${won(x.first)}`,lines:[['마지막 달',won(x.last)],['총 이자',won(x.totalInterest)],['총 상환액',won(x.totalPayment)]],raw:x})}
  else if(id==='salary'){const [year,dep,nonTax]=(mode||'2026|1|200000').split('|').map(Number);const x=salaryEstimate(n(a),year,nonTax,dep);done({main:`월 예상 ${won(x.net)}`,lines:[['세전 월급',won(x.gross)],['국민연금',won(x.pension)],['건강보험',won(x.health)],['장기요양',won(x.care)],['고용보험',won(x.employment)],['소득세',won(x.income)],['지방소득세',won(x.local)],['공제 합계',won(x.total)]],note:'간이 추정치입니다. 실제 원천징수액은 부양가족, 비과세 항목, 회사 처리 및 연말정산에 따라 달라집니다.',raw:x})}
 }
 const inputs=()=>{switch(id){
  case'date':return <><Field label="시작일" type="date" value={a} onChange={setA}/><Field label="종료일" type="date" value={b} onChange={setB}/></>
  case'age':return <><Field label="생년월일" type="date" value={a} onChange={setA}/><Field label="기준일" type="date" value={b||today} onChange={setB}/></>
  case'dday':return <Field label="목표일" type="date" value={a} onChange={setA}/>
  case'percent':return <><Select label="계산 방식" value={mode||'change'} onChange={setMode} options={[["change","증감률"],["discount","할인 가격"]]}/><Field label={mode==='discount'?'원래 가격':'기준값'} value={a} onChange={setA}/><Field label={mode==='discount'?'할인율(%)':'변경값'} value={b} onChange={setB}/></>
  case'unit':return <><Select label="변환" value={mode||'pyeong'} onChange={setMode} options={[["pyeong","평 → ㎡"],["meter","m → cm"],["km","km → m"],["kg","kg → g"],["lb","lb → kg"]]}/><Field label="값" value={a} onChange={setA}/></>
  case'ratio':return <><Field label="원본 너비" value={a} onChange={setA}/><Field label="원본 높이" value={b} onChange={setB}/><Field label="새 너비" value={c} onChange={setC}/></>
  case'text':return <label className="field full"><span>텍스트</span><textarea rows={8} value={a} onChange={e=>setA(e.target.value)} placeholder="여기에 글을 붙여 넣으세요."/></label>
  case'random':return <><Select label="방식" value={mode||'pick'} onChange={setMode} options={[["pick","한 명 추첨"],["team","팀 나누기"]]}/><label className="field full"><span>이름 (쉼표 또는 줄바꿈)</span><textarea value={a} onChange={e=>setA(e.target.value)}/></label>{mode==='team'&&<Field label="팀 수" value={b} onChange={setB}/>}</>
  case'timezone':return <><Field label="날짜와 시간" type="datetime-local" value={a} onChange={setA}/><Select label="변환할 도시" value={mode||'Asia/Seoul'} onChange={setMode} options={[["Asia/Seoul","서울"],["Asia/Tokyo","도쿄"],["America/New_York","뉴욕"],["America/Los_Angeles","로스앤젤레스"],["Europe/London","런던"],["Europe/Paris","파리"]]}/></>
  case'travel':return <><Field label="총 경비" value={a} onChange={setA}/><Field label="인원" value={b} onChange={setB}/><Select label="분담 방식" value={mode||'equal'} onChange={setMode} options={[["equal","균등"],["weighted","가중치"]]}/>{mode==='weighted'&&<Field label="가중치 (예: 1,2,1)" type="text" value={c} onChange={setC}/>}</>
  case'fuel':return <><Field label="주행 거리 (km)" value={a} onChange={setA}/><Field label="연비 (km/L)" value={b} onChange={setB}/><Field label="유가 (원/L)" value={c} onChange={setC}/></>
  case'saving':return <><Field label="목표 금액" value={a} onChange={setA}/><Field label="현재 금액" value={b} onChange={setB}/><Field label="월 저축액" value={c} onChange={setC}/></>
  case'study':return <><Field label="전체 분량" value={a} onChange={setA}/><Field label="완료 분량" value={b} onChange={setB}/><Field label="남은 일수" value={c} onChange={setC}/><Select label="단위" value={mode||'쪽'} onChange={setMode} options={[["쪽","쪽"],["분","분"],["강","강"]]}/></>
  case'schedule':return <><Field label="첫 일정" type="date" value={a} onChange={setA}/><Field label="횟수" value={b} onChange={setB}/><Field label="간격 (일)" value={c} onChange={setC}/></>
  case'loan':return <><Field label="대출 원금" value={a} onChange={setA}/><Field label="연 이자율 (%)" step="0.01" value={b} onChange={setB}/><Field label="기간 (개월)" value={c} onChange={setC}/><Select label="상환 방식" value={mode||'annuity'} onChange={setMode} options={[["annuity","원리금균등"],["principal","원금균등"],["bullet","만기일시"]]}/></>
  case'salary':return <><Field label="연봉 (세전)" value={a} onChange={setA}/><Select label="조건" value={mode||'2026|1|200000'} onChange={setMode} options={[["2026|1|200000","2026 · 본인 1명 · 비과세 20만원"],["2025|1|200000","2025 · 본인 1명 · 비과세 20만원"],["2026|2|200000","2026 · 부양가족 2명 · 비과세 20만원"],["2026|1|0","2026 · 본인 1명 · 비과세 없음"]]}/></>
  default:return null}}
 return <><div className="form-grid">{inputs()}<button className="primary" onClick={calculate}>계산하기</button></div>{result&&<Result {...result}/>}</>
}

function Minimum(){return <div className="table-wrap"><table><thead><tr><th>연도</th><th>시급</th><th>일급(8h)</th><th>월급(209h)</th></tr></thead><tbody>{minimumWages.map(x=><tr key={x.year}><td>{x.year}</td><td>{won(x.hourly)}</td><td>{won(x.daily)}</td><td>{won(x.monthly)}</td></tr>)}</tbody></table><p className="source">최저임금위원회 공식 결정 현황 기준. 2027년은 2026년 8월 고시된 적용 예정액입니다.</p></div>}
function SalaryTable(){
 const [year,setYear]=useState(2026),[dependents,setDependents]=useState(1),[nonTax,setNonTax]=useState(200000)
 const [period,setPeriod]=useState<'first'|'second'>('second')
 const [detail,setDetail]=useState(false)
 const rows=useMemo(()=>Array.from({length:16},(_,i)=>30000000+i*5000000).map(annual=>({annual,...salaryEstimate(annual,year,nonTax,dependents,period)})),[year,dependents,nonTax,period])
 const r=salaryRateInfo(year,period)
 return <><div className="table-filters"><Select label="적용 연도" value={String(year)} onChange={v=>setYear(Number(v))} options={[["2026","2026"],["2025","2025"],["2024","2024"],["2023","2023"]]}/><Select label="적용 시기" value={period} onChange={v=>setPeriod(v as 'first'|'second')} options={[["first","1~6월"],["second","7~12월"]]}/><Select label="부양가족 (본인 포함)" value={String(dependents)} onChange={v=>setDependents(Number(v))} options={[["1","1명"],["2","2명"],["3","3명"],["4","4명"]]}/><Select label="월 비과세액" value={String(nonTax)} onChange={v=>setNonTax(Number(v))} options={[["0","없음"],["100000","10만원"],["200000","20만원"]]}/></div><div className="salary-toolbar"><div className="rate-note"><b>{year}년 {period==='first'?'1~6월':'7~12월'} 근로자 부담 기준</b><span>국민연금 {num(r.pension*100,3)}%</span><span>연금 상한 {won(pensionCaps[year][period])}</span><span>건강보험 {num(r.health*100,4)}%</span><span>장기요양 {num(r.care*100,4)}%</span><span>고용보험 {num(r.employment*100,2)}%</span></div><div className="view-toggle"><button className={!detail?'selected':''} onClick={()=>setDetail(false)}>간단히 보기</button><button className={detail?'selected':''} onClick={()=>setDetail(true)}>공제 상세</button></div></div>{detail?<div className="table-wrap salary-table"><table><thead><tr><th>연봉</th><th>월 세전</th><th>국민연금</th><th>건강보험</th><th>장기요양</th><th>고용보험</th><th>소득세</th><th>지방소득세</th><th>공제 합계</th><th>월 실수령 예상</th></tr></thead><tbody>{rows.map(x=><tr key={x.annual}><td>{won(x.annual)}</td><td>{won(x.gross)}</td><td>{won(x.pension)}</td><td>{won(x.health)}</td><td>{won(x.care)}</td><td>{won(x.employment)}</td><td>{won(x.income)}</td><td>{won(x.local)}</td><td>{won(x.total)}</td><td className="net">{won(x.net)}</td></tr>)}</tbody></table></div>:<div className="table-wrap salary-simple"><table><thead><tr><th>연봉</th><th>월 세전</th><th>4대 보험</th><th>세금</th><th>월 실수령</th></tr></thead><tbody>{rows.map(x=><tr key={x.annual}><td>{won(x.annual)}</td><td>{won(x.gross)}</td><td>{won(x.pension+x.health+x.care+x.employment)}</td><td>{won(x.income+x.local)}</td><td className="net">{won(x.net)}</td></tr>)}</tbody></table></div>}<p className="source">사회보험은 선택 연도의 근로자 부담 요율과 선택한 반기의 국민연금 기준소득월액 상한을 적용합니다. 소득세는 2020~2022년에는 2020년 개정표, 2023년 이후에는 2023년 개정 근로소득 간이세액표에서 월 과세급여와 부양가족 수로 조회합니다. 실제 급여명세와 연말정산 결과는 회사 처리와 개인 공제에 따라 달라질 수 있습니다.</p></>
}

type DisplayHistory=History|LocalHistory
type CachedAuth='member'|'guest'|'checking'
const cachedAuth=():CachedAuth=>(sessionStorage.getItem('wonderlife:auth') as CachedAuth|null)||(sessionStorage.getItem('wonderlife:member')==='1'?'member':'checking')
const historyMain=(item:DisplayHistory)=>{try{return JSON.parse(item.resultJson).main||'계산 결과 보기'}catch{return '계산 결과 보기'}}
const validHistory=(item:DisplayHistory)=>!/(NaN|Infinity|undefined)/.test(historyMain(item))
const historyTime=(value:string)=>{const date=new Date(value),pad=(v:number)=>String(v).padStart(2,'0');return `${date.getFullYear()}.${pad(date.getMonth()+1)}.${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`}
const modeNames:Record<string,string>={change:'증감률',discount:'할인',pyeong:'평→㎡',meter:'m→cm',km:'km→m',kg:'kg→g',lb:'lb→kg',pick:'추첨',team:'팀 나누기',equal:'균등',weighted:'가중',annuity:'원리금균등',principal:'원금균등',bullet:'만기일시'}
const historyInput=(item:DisplayHistory)=>{try{const value=JSON.parse(item.inputJson) as Record<string,string>;const clean=(v?:string)=>String(v||'').replace(/\s+/g,' ').trim();const parts=[clean(value.a),clean(value.b),clean(value.c),modeNames[value.mode]||clean(value.mode)].filter(Boolean);return parts.length?parts.join(' · '):'입력값 없음'}catch{return '입력값 확인 불가'}}
function MainApp(){
 const [initialAuth]=useState<CachedAuth>(cachedAuth)
 const [active,setActive]=useState('loan');const [query,setQuery]=useState('');const [member,setMember]=useState<Member|null>(()=>initialAuth==='member'?{id:0,email:''}:null);const [authReady,setAuthReady]=useState(initialAuth!=='checking');const [historyLoading,setHistoryLoading]=useState(initialAuth!=='guest');const [history,setHistory]=useState<DisplayHistory[]>(()=>initialAuth==='guest'?loadLocalHistories():[]);const [saved,setSaved]=useState('')
 const [featured]=useState(()=>calculatorTools[Math.floor(Math.random()*calculatorTools.length)])
 useEffect(()=>{let alive=true;const local=loadLocalHistories();const prefetched=!local.length?api.histories().then(value=>({value,error:false as const})).catch(()=>({value:[] as History[],error:true as const})):null;(async()=>{try{const m=await api.me();if(!alive)return;sessionStorage.removeItem('wonderlife:member');sessionStorage.setItem('wonderlife:auth','member');setMember(m);setAuthReady(true);setHistoryLoading(true);try{let remote:History[];if(local.length)remote=await api.importHistories(local.map(({calculatorType,title,inputJson,resultJson})=>({calculatorType,title,inputJson,resultJson})));else{const fetched=await prefetched!;if(fetched.error)throw new Error('history load failed');remote=fetched.value}if(alive){clearLocalHistories();setHistory(remote)}}catch{if(alive){setSaved('로컬 이력을 계정으로 옮기지 못했습니다. 잠시 후 새로고침해 주세요.');try{setHistory(await api.histories())}catch{setHistory([])}}}finally{if(alive)setHistoryLoading(false)}}catch{if(alive){sessionStorage.removeItem('wonderlife:member');sessionStorage.setItem('wonderlife:auth','guest');setMember(null);setAuthReady(true);setHistory(local);setHistoryLoading(false)}}})();return()=>{alive=false}},[])
 const visible=calculatorTools.filter(x=>(x.title+x.desc).includes(query));const tool=tools.find(x=>x.id===active)!;const displayHistory=history.filter(validHistory)
 const activeHistory=displayHistory.filter(x=>x.calculatorType===active).slice(0,10)
 const record=async(title:string,input:unknown,result:unknown)=>{const body:SaveHistory={calculatorType:active,title,inputJson:JSON.stringify(input),resultJson:JSON.stringify(result)};if(member){try{const item=await api.save(body);setHistory(v=>[item,...v.filter(x=>x.calculatorType!==active||x.id!==item.id)].filter((item,index,all)=>all.slice(0,index+1).filter(x=>x.calculatorType===item.calculatorType).length<=10));setSaved('계정에 자동 저장했습니다.')}catch{setSaved('저장하지 못했습니다. 다시 계산해 주세요.')}}else{setHistory(addLocalHistory(body));setSaved('이 브라우저에 자동 저장했습니다.')}setTimeout(()=>setSaved(''),2200)}
 const remove=async(item:DisplayHistory)=>{if(typeof item.id==='number'){await api.remove(item.id);setHistory(v=>v.filter(x=>x.id!==item.id))}else setHistory(removeLocalHistory(item.id))}
 const HistoryRows=({items}:{items:DisplayHistory[]})=><div className="history-list">{items.map(item=><article key={item.id}><b title={item.title}>{item.title}</b><span className="history-input" title={historyInput(item)}>{historyInput(item)}</span><strong title={historyMain(item)}>{historyMain(item)}</strong><small>{historyTime(item.createdAt)}</small><button aria-label={`${item.title} 이력 삭제`} onClick={()=>void remove(item)}>삭제</button></article>)}</div>
 const login=()=>{sessionStorage.setItem('wonderlife:auth','checking');setHistory([]);setHistoryLoading(true)}
 const logout=(event:MouseEvent<HTMLAnchorElement>)=>{event.preventDefault();sessionStorage.removeItem('wonderlife:member');sessionStorage.setItem('wonderlife:auth','guest');setMember(null);setAuthReady(true);setHistory(loadLocalHistories());setHistoryLoading(false);requestAnimationFrame(()=>window.location.assign('/logout'))}
 const goTop=()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})
 return <div className="app"><header><a className="brand" href="#"><i>W</i><span>WonderLife<small>Everyday answers, made simple.</small></span></a><nav><a href="#tools">계산기</a><a href="#data">생활 자료</a><a href="#history">계산 이력</a></nav><div className="account">{!authReady?<span className="account-loading">로그인 확인 중…</span>:member?<><span>{member.email}</span><a href="/logout" onClick={logout}>로그아웃</a></>:<a className="login" href="/oauth2/authorization/google" onClick={login}>Google로 로그인</a>}</div></header>
 <main><section className="hero"><div><p className="eyebrow">DAILY TOOLKIT</p><h1>복잡한 계산을<br/><em>가볍고 정확하게.</em></h1><p>날짜부터 대출까지. 필요한 답만 빠르게 확인하세요.</p></div><div className="hero-card"><span>오늘 가장 많이 찾는 계산</span><b>{featured.title}</b><button onClick={()=>{setActive(featured.id);document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'})}}>바로 계산하기 →</button></div></section>
 <section id="tools" className="catalog"><div className="section-title"><div><small>ALL CALCULATORS</small><h2>무엇을 계산할까요?</h2></div><input aria-label="계산기 검색" placeholder="계산기 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="cards">{visible.map(x=><button className={'tool-card '+(active===x.id?'active':'')} key={x.id} onClick={()=>{setActive(x.id);document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'})}}><i>{x.icon}</i><span><b>{x.title}</b><small>{x.desc}</small></span><em>→</em></button>)}</div></section>
 <section id="data" className="life-data"><div className="section-title"><div><small>LIFE DATA</small><h2>생활 자료</h2><p>공식 기준 이력과 계산 원리를 한곳에서 확인하세요.</p></div></div><div className="data-cards"><button onClick={()=>{setActive('minimum');document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'})}}><i>₩</i><span><b>연도별 최저시급</b><small>2011년부터 공식 시급·일급·월 환산액</small></span><em>표 보기 →</em></button><button onClick={()=>{setActive('salaryTable');document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'})}}><i>급</i><span><b>연도별 연봉 실수령액</b><small>2020~2026년 보험료·세금 상세 비교</small></span><em>표 보기 →</em></button><a href="/guides"><i>?</i><span><b>계산 가이드</b><small>계산식, 차이가 나는 이유와 자주 묻는 질문</small></span><em>읽기 →</em></a></div></section>
 <section id="workspace" className="workspace"><div className="calc-head"><i>{tool.icon}</i><div><small>{tool.group}</small><h2>{tool.title}</h2><p>{tool.desc}</p></div></div><Calculator id={active} onCalculated={(title,input,result)=>void record(title,input,result)}/>{saved&&<div className="save-row"><b>{saved}</b></div>}{activeHistory.length>0&&<div className="calculator-history"><div className="history-heading"><div><small>RECENT 10</small><h3>{tool.title} 최근 이력</h3></div><span>{member?'계정에 저장됨':'이 브라우저에만 저장됨'}</span></div><HistoryRows items={activeHistory}/></div>}</section>
 <section id="history" className="history"><div className="section-title"><div><small>ALL HISTORY</small><h2>전체 계산 이력</h2><p>{member?'로그인 계정에 자동 저장된 계산입니다.':'로그인하면 이 브라우저의 이력을 계정으로 옮겨 다른 기기에서도 볼 수 있습니다.'}</p></div></div>{historyLoading?<div className="empty-history history-loading">계산 이력을 불러오는 중…</div>:displayHistory.length?<HistoryRows items={displayHistory}/>:<div className="empty-history">아직 계산 이력이 없습니다. 계산기를 실행하면 자동으로 기록됩니다.</div>}</section>
 </main><button className="top-button" onClick={goTop} aria-label="페이지 맨 위로 이동"><span>↑</span> 맨 위</button><footer><b>WonderLife</b><span>계산 결과는 참고용이며 중요한 금융·세무 결정 전 공식 기관 또는 전문가와 확인하세요.</span><nav className="footer-links"><a href="/guides">계산 가이드</a><a href="/about">서비스 소개</a><a href="/privacy">개인정보처리방침</a><a href="/terms">이용약관</a><a href="/contact">문의</a></nav></footer></div>}

const trustPages:Record<string,{title:string;body:string[]}>= {
 '/about':{title:'WonderLife 소개',body:['WonderLife는 날짜, 단위, 비용과 대출처럼 일상에서 자주 만나는 계산을 쉽고 투명하게 제공하는 생활 도구 모음입니다.','계산 결과와 함께 적용한 조건과 공식 자료의 기준 연도를 표시하며, 사용자가 결과의 의미와 한계를 이해할 수 있도록 설명합니다. 비회원의 최근 계산은 현재 브라우저에만 보관하고, Google 로그인 시 계정 이력으로 옮겨 본인만 조회하거나 삭제할 수 있습니다.']},
 '/privacy':{title:'개인정보처리방침',body:['비회원이 실행한 계산의 입력값과 결과는 서버로 전송하지 않고 현재 브라우저의 로컬 저장소에 계산기별 최근 10개까지 보관합니다. Google 로그인 시 로컬 계산 이력을 계정 DB로 이관한 뒤 브라우저 사본을 삭제하며, 이후 계산 이력은 계정에 자동 저장합니다.','Google 로그인 회원은 계정 식별에 필요한 Google 계정 식별자와 이메일 및 계산 이력을 서버에 보관합니다. 저장된 계산 이력은 로그인한 본인만 조회하고 삭제할 수 있습니다. 광고가 활성화된 경우 Google AdSense가 쿠키 또는 유사 기술을 사용할 수 있으며, 자세한 내용은 Google의 광고 개인정보 안내를 따릅니다. 계정 및 데이터 삭제 문의는 meet.wonderlife@gmail.com으로 접수할 수 있습니다.']},
 '/terms':{title:'이용약관 및 계산 안내',body:['WonderLife의 계산 결과는 일반적인 정보 제공을 위한 참고값입니다. 대출 실제 납입액은 금융기관의 일수 계산, 중도상환, 수수료와 계약 조건에 따라 달라질 수 있습니다. 급여 실수령액은 회사 처리, 개인 공제, 보험 기준소득 결정과 연말정산에 따라 달라질 수 있습니다.','중요한 금융·세무·법률 결정을 내리기 전에는 해당 기관의 공식 안내 또는 전문가의 확인을 권합니다. 서비스의 계산 오류를 발견하면 입력 조건과 함께 문의해 주세요.']},
 '/contact':{title:'문의',body:['계산 기준, 오류 제보, 개인정보 또는 서비스 관련 문의는 meet.wonderlife@gmail.com으로 보내주세요. 계산 오류 제보 시 계산기 이름, 입력 조건, 기대한 결과와 참고한 공식 자료를 알려주시면 확인에 도움이 됩니다.']}
}
function TrustPage({page}:{page:{title:string;body:string[]}}){return <div className="app"><header><a className="brand" href="/"><i>W</i><span>WonderLife<small>Everyday answers, made simple.</small></span></a></header><main className="trust-page"><a href="/">← 계산기로 돌아가기</a><h1>{page.title}</h1>{page.body.map((p,i)=><p key={i}>{p}</p>)}</main></div>}
function GuidePage(){const path=window.location.pathname;const slug=path.split('/')[2];const guide=guides.find(x=>x.slug===slug);useEffect(()=>{document.title=guide?`${guide.title} | WonderLife`:'계산 가이드 | WonderLife'},[guide]);if(!guide)return <GuideIndex/>;return <div className="app"><header><a className="brand" href="/"><i>W</i><span>WonderLife<small>Everyday answers, made simple.</small></span></a></header><article className="guide-page"><a href="/guides">← 계산 가이드</a><p className="eyebrow">CALCULATION GUIDE</p><h1>{guide.title}</h1><p className="guide-lead">{guide.summary}</p>{guide.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}<section><h2>자주 묻는 질문</h2>{guide.faq.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</section><p className="guide-updated">마지막 검토: 2026년 8월 · 계산 결과는 참고용입니다.</p></article></div>}
function GuideIndex(){useEffect(()=>{document.title='계산 가이드 | WonderLife'},[]);return <div className="app"><header><a className="brand" href="/"><i>W</i><span>WonderLife<small>Everyday answers, made simple.</small></span></a></header><main className="guide-index"><a href="/">← 계산기로 돌아가기</a><p className="eyebrow">WONDERLIFE GUIDES</p><h1>계산을 이해하는 생활 가이드</h1><p>공식 기준, 계산식, 결과가 달라지는 이유를 도구별로 정리했습니다.</p><div className="guide-grid">{guides.map(g=><a href={`/guides/${g.slug}`} key={g.slug}><small>{g.category}</small><h2>{g.title}</h2><p>{g.summary}</p><b>읽어보기 →</b></a>)}</div></main></div>}
export default function App(){const path=window.location.pathname;const page=trustPages[path];return path.startsWith('/guides')?<GuidePage/>:page?<TrustPage page={page}/>:<MainApp/>}
