import {useEffect,useState} from 'react'
import {educationApi,type EducationSchoolDetail} from './api'
import {metricLabels} from './educationContent'
import SiteHeader from './SiteHeader'
import EducationNav from './EducationNav'
import TopButton from './TopButton'

export default function EducationSchoolPage(){
 const parts=window.location.pathname.split('/'),office=decodeURIComponent(parts[4]||''),school=decodeURIComponent(parts[5]||'')
 const [detail,setDetail]=useState<EducationSchoolDetail|null>(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;educationApi.schoolDetail(office,school).then(value=>{if(active)setDetail(value)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'학교 조회 실패')});return()=>{active=false}},[office,school])
 useEffect(()=>{document.title=`${detail?.school.schoolName||'학교별'} 통계 | WonderLife`;document.querySelector('meta[name="description"]')?.setAttribute('content',`${detail?.school.schoolName||'학교'} 학생·교원·학급 지표, 수집된 급식과 학사일정을 확인하세요.`);let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=window.location.origin+window.location.pathname},[detail])
 return <div className="app"><SiteHeader/><main className="education-page"><EducationNav/>{error?<p role="alert">{error}</p>:!detail?<p role="status">학교 통계를 불러오는 중…</p>:<><header className="education-heading"><div><p className="eyebrow">{detail.school.educationOfficeName} · {detail.school.schoolKind}</p><h1>{detail.school.schoolName}</h1><p>{detail.school.address}</p><p>{detail.school.foundationType} · {detail.school.coeducationType}{detail.school.openedOn&&` · 설립 ${detail.school.openedOn}`}</p></div></header><section className="education-page-copy"><h2>연도별 학생·교육환경 지표</h2>{detail.metrics.length?<div className="education-table-wrap"><table><thead><tr><th>연도</th><th>지표</th><th>공시 값</th></tr></thead><tbody>{detail.metrics.map(row=><tr key={`${row.year}-${row.metric}`}><td>{row.year}</td><td>{metricLabels[row.metric]||row.metric}</td><td>{Number(row.value).toLocaleString()}</td></tr>)}</tbody></table></div>:<p>연결된 공시 지표가 없습니다. 미수집이거나 기관 간 학교코드 연결 검토가 필요한 상태이며 0을 뜻하지 않습니다.</p>}<p>학교알리미와 NEIS는 학교코드가 달라 교육청·학교명·학교급에 단일 후보가 있는 경우에만 연결합니다.</p><a href={`/data/education/disclosures?name=${encodeURIComponent(detail.school.schoolName)}`}>학교 공시 원문 전체 조회 →</a></section><section className="education-page-copy"><h2>수집된 급식 전체 ({detail.meals.length.toLocaleString()}건)</h2>{detail.meals.length?<div className="education-table-wrap"><table><thead><tr><th>날짜</th><th>구분</th><th>식단</th><th>열량</th></tr></thead><tbody>{detail.meals.map((row,i)=><tr key={`${row.date}-${row.name}-${i}`}><td>{row.date}</td><td>{row.name}</td><td>{row.menu}</td><td>{row.calorie||'미제공'}</td></tr>)}</tbody></table></div>:<p>수집된 급식이 없습니다. 학교의 미제공 또는 수집 대기일 수 있습니다.</p>}</section><section className="education-page-copy"><h2>수집된 학사일정 전체 ({detail.schedules.length.toLocaleString()}건)</h2>{detail.schedules.length?<div className="education-table-wrap"><table><thead><tr><th>날짜</th><th>일정</th><th>상세</th></tr></thead><tbody>{detail.schedules.map((row,i)=><tr key={`${row.date}-${row.name}-${i}`}><td>{row.date}</td><td>{row.name}</td><td>{row.content}</td></tr>)}</tbody></table></div>:<p>수집된 학사일정이 없습니다.</p>}<p>조회 범위는 최근 1년부터 앞으로 90일입니다. 실제 일정은 학교 안내를 우선하세요.</p></section></>}</main><TopButton/></div>
}
