import {useEffect,useState} from 'react'
import SiteHeader from './SiteHeader'
export function studentChange(previous:number,current:number){return previous>0?(current-previous)/previous*100:null}
export default function EducationReadingGuide(){
 const [previous,setPrevious]=useState('500'),[current,setCurrent]=useState('450')
 const valid=/^\d+$/.test(previous)&&/^\d+$/.test(current)&&Number(previous)<=10000000&&Number(current)<=10000000
 const change=valid?studentChange(Number(previous),Number(current)):null
 useEffect(()=>{document.title='교육 통계 읽는 법 | WonderLife';document.querySelector('meta[name="description"]')?.setAttribute('content','학교 수와 학생 수, 학급 밀도, 동일 학교 증감률을 해석하는 방법과 직접 계산 예제를 확인하세요.');let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=window.location.origin+'/guides/education-statistics'},[])
 return <div className="app"><SiteHeader/><main className="guide-page"><a href="/guides">← 가이드</a><p className="eyebrow">EDUCATION DATA GUIDE</p><h1>교육 통계, 숫자보다 먼저 확인할 것</h1><p className="guide-lead">학교 통계는 같은 기준의 학교와 연도를 비교해야 의미가 있습니다. 수집된 합계와 전국 전수 현황은 구분해서 읽으세요.</p>
 <section><h2>1. 합계가 늘었다고 학생이 증가한 것은 아닙니다</h2><p>지난해 10개 학교, 올해 20개 학교가 수집됐다면 올해 합계가 커지는 것은 자연스럽습니다. 학생 변화는 두 연도에 모두 자료가 있는 동일 학교끼리 비교해야 합니다. 비교 학교 수가 작다면 해당 지역 전체의 변화로 일반화하지 마세요.</p><p>예를 들어 두 학교의 학생 수가 각각 100명에서 90명, 900명에서 990명으로 바뀌면 전체는 1,000명에서 1,080명으로 8% 증가합니다. 학교별 증감률 −10%와 +10%를 단순 평균한 0%는 전체 증감률이 아닙니다.</p></section>
 <section><h2>2. 증감률 직접 확인하기</h2><p>증감률 = (현재 학생 수 − 이전 학생 수) ÷ 이전 학생 수 × 100. 아래 값은 설명용 입력이며 실제 학교 통계가 아닙니다. 입력은 저장하지 않습니다.</p><div className="form-grid"><label className="field">이전 학생 수<input inputMode="numeric" value={previous} onChange={e=>setPrevious(e.target.value)}/></label><label className="field">현재 학생 수<input inputMode="numeric" value={current} onChange={e=>setCurrent(e.target.value)}/></label></div><p role="status">{!valid?'0~10,000,000 사이의 정수 인원을 입력하세요.':change===null?'이전 학생이 0명이면 증감률은 정의할 수 없습니다.':`학생 수 ${Number(current)-Number(previous)}명 변화 · 증감률 ${change.toFixed(2)}%`}</p></section>
 <section><h2>3. 학급당 학생 수는 합계로 계산합니다</h2><p>학생 100명·5학급 학교와 학생 900명·30학급 학교의 학급당 학생 수는 각각 20명, 30명입니다. 지역 전체는 1,000명 ÷ 35학급 = 약 28.57명입니다. 학교별 비율의 단순 평균인 25명과 다릅니다.</p><p>학생 수와 학급 수가 모두 있는 같은 학교만 분자·분모에 포함해야 합니다. 교원 1인당 학생 수도 동일한 원칙을 사용하며 교원 분류와 기준일이 다른 공시를 섞지 않아야 합니다.</p></section>
 <section><h2>4. 미수집과 실제 0건은 다릅니다</h2><p>학생 수가 비어 있다는 것은 학생이 없다는 뜻이 아닙니다. API 제공 범위, 수집 진행률, 기관 간 학교 연결 상태를 확인해야 합니다. NEIS와 학교알리미는 학교 식별자가 달라 모호한 연결은 제외합니다. 현재 학교 수를 과거 연도의 학교 수로 읽지 마세요.</p></section>
 <section><h2>5. 급식과 일정 집계의 한계</h2><p>메뉴 출현 횟수는 식단에 얼마나 자주 등장했는지를 뜻하며 학생 선호도나 실제 섭취량이 아닙니다. 열량은 제공된 유효 값이 있는 급식만 집계합니다. 날짜별 학교 행사 수 역시 수집 학교 범위의 결과이지 전국 모든 학교의 확정 일정은 아닙니다. 실제 일정과 식단은 학교 공지를 우선하세요.</p></section>
 <section><h2>자료 확인과 다음 탐색</h2><p>원천 자료는 <a href="https://open.neis.go.kr/" target="_blank" rel="noreferrer">NEIS 교육정보 개방 포털</a>과 <a href="https://www.schoolinfo.go.kr/" target="_blank" rel="noreferrer">학교알리미</a>에서 확인할 수 있습니다. WonderLife는 수집값을 임의의 학교 종합 순위로 변환하지 않습니다.</p><nav className="reading-links" aria-label="관련 통계"><a href="/data/education/trends">동일 학교 학생 변화</a><a href="/data/education/regions">지역 비교</a><a href="/data/education/disclosures">공시 원문 확인</a><a href="/data/education/collection-status">수집 범위 확인</a></nav></section><p className="guide-updated">작성: WonderLife · 2026-09-15 · 통계 해석 안내이며 개별 학교 평가가 아닙니다.</p></main></div>
}
