import {useEffect,useMemo,useState} from 'react'
import SiteHeader from './SiteHeader'
import TopButton from './TopButton'
import EducationNav from './EducationNav'
import {schoolPath,metricLabels} from './educationContent'
import {educationApi,type EducationDailySummary,type EducationDisclosureSummary,type EducationSchoolDetail,type EducationRatio,type SchoolInfo} from './api'

type Metric='students'|'classSize'|'schools'
type Region={name:string;short:string;code:string;students:number;change:number;classSize:number;schools:number;schoolChange:number}
type EducationView='hub'|'schools'|'regions'|'daily'|'collection'

const educationPages:Record<EducationView,{path:string;title:string;heading:string;description:string}>={
 hub:{path:'/data/education',title:'대한민국 교육·학교 통계',heading:'교육 통계',description:'전국 학교, 지역별 학생·학급 현황, 급식과 학사일정을 공식 데이터로 확인하세요.'},
 schools:{path:'/data/education/schools',title:'전국 학교 검색과 학교별 통계',heading:'학교 찾기',description:'학교명을 검색해 기본정보, 학생·교원·학급 지표, 급식과 학사일정을 확인하세요.'},
 regions:{path:'/data/education/regions',title:'지역별 학생 수·학교 수 비교',heading:'지역 비교',description:'시도별 학생 수, 학교 수와 학급당 학생 수를 연도별로 비교하세요.'},
 daily:{path:'/data/education/meals-schedules',title:'전국 학교 급식·학사일정 통계',heading:'급식·일정',description:'오늘 수집된 학교 급식과 앞으로 30일간의 학사일정 통계를 확인하세요.'},
 collection:{path:'/data/education/collection-status',title:'교육 통계 데이터 수집 현황',heading:'데이터 안내',description:'NEIS와 학교알리미 일배치의 수집 범위, 기준일과 백필 진행률을 확인하세요.'},
}
const educationView=():EducationView=>{const path=window.location.pathname;if(path.endsWith('/schools'))return 'schools';if(path.endsWith('/regions'))return 'regions';if(path.endsWith('/meals-schedules'))return 'daily';if(path.endsWith('/collection-status'))return 'collection';return 'hub'}

const regions:Region[]=[
 {name:'서울특별시',short:'서울',code:'11',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'부산광역시',short:'부산',code:'26',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'대구광역시',short:'대구',code:'27',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'인천광역시',short:'인천',code:'28',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'전남광주통합특별시',short:'전남광주',code:'12',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'대전광역시',short:'대전',code:'30',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'울산광역시',short:'울산',code:'31',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'세종특별자치시',short:'세종',code:'36',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'경기도',short:'경기',code:'41',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'충청북도',short:'충북',code:'43',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'충청남도',short:'충남',code:'44',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'경상북도',short:'경북',code:'47',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'경상남도',short:'경남',code:'48',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'제주특별자치도',short:'제주',code:'50',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'강원특별자치도',short:'강원',code:'51',students:0,change:0,classSize:0,schools:0,schoolChange:0},{name:'전북특별자치도',short:'전북',code:'52',students:0,change:0,classSize:0,schools:0,schoolChange:0},
]

const metricInfo:Record<Metric,{label:string;value:(region:Region)=>number;format:(value:number)=>string}>={
 students:{label:'학생 수',value:r=>r.students,format:v=>`${Math.round(v).toLocaleString()}명`},
 classSize:{label:'학급당 학생 수',value:r=>r.classSize,format:v=>`${v.toFixed(1)}명`},
 schools:{label:'학교 수',value:r=>r.schools,format:v=>`${v.toLocaleString()}개교`},
}

export default function EducationStatisticsPage(){
 const view=educationView(),page=educationPages[view]
 const [dataError,setDataError]=useState('')
 const [ratios,setRatios]=useState<EducationRatio[]>([])
 const [metric,setMetric]=useState<Metric>('students'),[year,setYear]=useState(String(new Date().getFullYear())),[query,setQuery]=useState('')
 const [schoolName,setSchoolName]=useState(''),[schools,setSchools]=useState<SchoolInfo[]>([]),[schoolMessage,setSchoolMessage]=useState(''),[loadingSchools,setLoadingSchools]=useState(false)
 const [schoolDetail,setSchoolDetail]=useState<EducationSchoolDetail|null>(null),[loadingDetail,setLoadingDetail]=useState(false)
 const [liveSchoolCounts,setLiveSchoolCounts]=useState<Record<string,number>>({}),[asOfDate,setAsOfDate]=useState('')
 const [dailySummary,setDailySummary]=useState<EducationDailySummary|null>(null)
 const [disclosure,setDisclosure]=useState<EducationDisclosureSummary|null>(null)
 useEffect(()=>{document.title=`${page.title} | WonderLife`;document.querySelector('meta[name="description"]')?.setAttribute('content',page.description);let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=window.location.origin+page.path},[page])
 useEffect(()=>{educationApi.summary().then(summary=>{const counts:Record<string,number>={};summary.regions.forEach(row=>{const target=regions.find(region=>row.region.includes(region.short)||(region.code==='12'&&(row.region.includes('광주')||row.region.includes('전남'))));if(target)counts[target.name]=(counts[target.name]||0)+row.schoolCount});setLiveSchoolCounts(counts);setAsOfDate(summary.asOfDate||'')}).catch(()=>setDataError('통계 조회에 실패했습니다. 표시된 빈 값은 실제 0을 의미하지 않습니다.'))},[])
 useEffect(()=>{educationApi.dailySummary().then(setDailySummary).catch(()=>{})},[])
 useEffect(()=>{educationApi.disclosureSummary(Number(year)).then(setDisclosure).catch(()=>{setDisclosure(null);setDataError('공시 지표 조회에 실패했습니다.')})},[year])
 useEffect(()=>{let active=true;educationApi.ratios(Number(year)).then(value=>{if(active)setRatios(value)}).catch(()=>{if(active){setRatios([]);setDataError('비율 지표 조회에 실패했습니다.')}});return()=>{active=false}},[year])
 const matchesRegion=(region:Region,code:string)=>code.startsWith(region.code)||(region.code==='12'&&(code.startsWith('29')||code.startsWith('46')))
 const pairedRatio=(region:Region,denominator:string)=>{const rows=ratios.filter(row=>matchesRegion(region,row.region)&&row.denominatorMetric===denominator);const numerator=rows.reduce((sum,row)=>sum+Number(row.numerator),0),divisor=rows.reduce((sum,row)=>sum+Number(row.denominator),0);return divisor>0?numerator/divisor:0}
 const disclosureValue=(region:Region,code:string)=>disclosure?.metrics.filter(row=>matchesRegion(region,row.region)&&row.metric===code).reduce((sum,row)=>sum+Number(row.value),0)||0
 const displayValue=(region:Region)=>metric==='schools'?(liveSchoolCounts[region.name]??0):metric==='students'?disclosureValue(region,'student_count'):pairedRatio(region,'class_count')
 const sorted=useMemo(()=>[...regions].filter(r=>r.name.includes(query.trim())||r.short.includes(query.trim())).sort((a,b)=>displayValue(b)-displayValue(a)),[metric,query,liveSchoolCounts,disclosure,ratios])
 const max=Math.max(...sorted.map(displayValue),1)
 const searchSchools=async()=>{if(schoolName.trim().length<2){setSchoolMessage('학교명을 두 글자 이상 입력하세요.');return}setLoadingSchools(true);setSchoolMessage('');try{const result=await educationApi.schoolSearch(schoolName.trim());setSchools(result);if(!result.length)setSchoolMessage('일치하는 학교가 없습니다.')}catch(error){setSchools([]);setSchoolMessage(error instanceof Error?error.message:'학교 정보를 불러오지 못했습니다.')}finally{setLoadingSchools(false)}}
 const openSchool=async(school:SchoolInfo)=>{setLoadingDetail(true);setSchoolMessage('');try{setSchoolDetail(await educationApi.schoolDetail(school.educationOfficeCode,school.schoolCode))}catch(error){setSchoolMessage(error instanceof Error?error.message:'학교 상세 정보를 불러오지 못했습니다.')}finally{setLoadingDetail(false)}}
 const total=(code:string)=>disclosure?.metrics.filter(row=>row.metric===code).reduce((sum,row)=>sum+Number(row.value),0)||0
 const students=total('student_count'),teachers=total('teacher_count'),books=total('library_books')
 const studentRanking=[...regions].map(region=>({region,value:disclosureValue(region,'student_count')})).filter(item=>item.value>0).sort((a,b)=>b.value-a.value)
 const densityRanking=[...regions].map(region=>({region,value:pairedRatio(region,'class_count')})).filter(item=>item.value>0).sort((a,b)=>b.value-a.value)
 return <div className="app education-app"><SiteHeader/><main className="education-page">
  <header className="education-heading"><div><p className="eyebrow">EDUCATION &amp; SCHOOL STATISTICS</p><h1>{page.heading}</h1><p>{page.description}</p></div><div className="education-source-status"><i/>{asOfDate?`NEIS ${asOfDate} 기준`:'초기 데이터 수집 필요'}</div></header>
  <EducationNav/>{dataError&&<p role="alert">{dataError}</p>}
  {view==='hub'&&<section className="education-route-cards"><a href={educationPages.schools.path}><small>SCHOOL SEARCH</small><h2>학교 찾기</h2><p>12,000여 개 학교의 기본정보와 수집된 학교별 통계를 확인합니다.</p><b>학교 찾기 →</b></a><a href={educationPages.regions.path}><small>REGIONAL DATA</small><h2>지역 비교</h2><p>연도와 지표를 선택해 시도별 학생 수와 교육환경을 비교합니다.</p><b>지역 비교 →</b></a><a href={educationPages.daily.path}><small>DAILY PULSE</small><h2>급식·일정</h2><p>오늘의 급식 제공 현황과 앞으로 30일간의 학교 일정을 봅니다.</p><b>오늘 통계 →</b></a><a href="/data/education/trends"><small>STUDENT TRENDS</small><h2>학생 변화</h2><p>동일 학교의 연도별 학생 수와 지역별 증감을 비교합니다.</p><b>변화 보기 →</b></a><a href="/data/education/disclosures"><small>DISCLOSURES</small><h2>공시 자료</h2><p>연도·학교·공시 유형별로 저장된 원문을 조회합니다.</p><b>공시 보기 →</b></a></section>}
  {view==='regions'&&<><section className="education-toolbar" aria-label="통계 조건"><label><span>기준 연도</span><select disabled={metric==='schools'} value={year} onChange={e=>setYear(e.target.value)}>{Array.from({length:3},(_,i)=>String(new Date().getFullYear()-i)).map(v=><option key={v}>{v}</option>)}</select></label><label><span>비교 지표</span><select value={metric} onChange={e=>setMetric(e.target.value as Metric)}><option value="students">학생 수</option><option value="classSize">학급당 학생 수</option><option value="schools">학교 수</option></select></label><label className="education-search"><span>지역 찾기</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="서울, 경기, 세종…"/></label></section><p className="education-demo"><b>데이터 안내</b> 모든 수치는 NEIS·학교알리미 일 배치 DB에서 조회합니다. 초기 백필 중에는 미수집·오류는 실제 0과 다릅니다. 학교 수는 선택 연도와 무관한 최신 학교 마스터 기준입니다.</p></>}
  {view==='schools'&&<><section className="school-search-panel"><header><div><small>NEIS LIVE DATA</small><h2>전국 학교 찾기</h2></div><span>NEIS 학교기본정보</span></header><form onSubmit={e=>{e.preventDefault();void searchSchools()}}><label><span className="sr-only">학교명</span><input value={schoolName} onChange={e=>setSchoolName(e.target.value)} placeholder="학교명을 입력하세요 (예: 서울초등학교)"/></label><button disabled={loadingSchools}>{loadingSchools?'검색 중…':'학교 검색'}</button></form>{schoolMessage&&<p className="school-search-message">{schoolMessage}</p>}{schools.length>0&&<div className="school-results">{schools.map(school=><article key={`${school.educationOfficeCode}-${school.schoolCode}`}><div><small>{school.educationOfficeName} · {school.schoolKind}</small><h3>{school.schoolName}</h3><p>{school.address}</p></div><div><span>{school.coeducationType}</span><a href={schoolPath(school.educationOfficeCode,school.schoolCode)}>학교 상세 →</a><button type="button" disabled={loadingDetail} onClick={()=>void openSchool(school)}>미리보기</button>{school.homepageUrl&&<a href={school.homepageUrl.startsWith('http')?school.homepageUrl:`https://${school.homepageUrl}`} target="_blank" rel="noreferrer">홈페이지 ↗</a>}</div></article>)}</div>}
  {schoolDetail&&<div className="school-detail"><header><div><small>{schoolDetail.school.educationOfficeName} · {schoolDetail.school.schoolKind}</small><h3>{schoolDetail.school.schoolName} 상세 통계</h3></div><button type="button" onClick={()=>setSchoolDetail(null)} aria-label="학교 상세 닫기">×</button></header><div className="school-detail-grid"><article><h4>학교알리미 지표</h4>{schoolDetail.metrics.length?schoolDetail.metrics.map(item=><p key={`${item.year}-${item.metric}`}><span>{item.year} · {metricLabels[item.metric]||item.metric}</span><b>{Number(item.value).toLocaleString()}</b></p>):<em>공시 백필 대기 중</em>}</article><article><h4>급식</h4>{schoolDetail.meals.length?schoolDetail.meals.map((item,index)=><p key={`${item.date}-${item.name}-${index}`}><span>{item.date} · {item.name}</span><b>{item.menu}</b></p>):<em>수집된 급식 없음</em>}</article><article><h4>학사일정</h4>{schoolDetail.schedules.length?schoolDetail.schedules.map((item,index)=><p key={`${item.date}-${item.name}-${index}`}><span>{item.date}</span><b>{item.name}</b></p>):<em>수집된 일정 없음</em>}</article></div></div>}</section></>}
  {view==='daily'&&<><section className="education-daily"><header><div><small>DAILY SCHOOL PULSE</small><h2>오늘의 급식·학사일정</h2></div><span>{dailySummary?.date||'수집 대기'}</span></header><div className="education-daily-kpis"><article><small>급식 데이터</small><b>{(dailySummary?.mealCount||0).toLocaleString()}건</b></article><article><small>급식 제공 학교</small><b>{(dailySummary?.mealSchoolCount||0).toLocaleString()}개교</b></article><article><small>30일 내 학사일정</small><b>{(dailySummary?.upcomingScheduleCount||0).toLocaleString()}건</b></article></div><div className="meal-type-bars">{dailySummary?.mealTypes.map((item)=><div key={item.label}><span>{item.label}</span><i style={{width:`${item.value/Math.max(...dailySummary.mealTypes.map(row=>row.value),1)*100}%`}}/><b>{item.value.toLocaleString()}건</b></div>)}</div></section>
  <section className="education-page-copy"><h2>급식 메뉴 출현 횟수·열량</h2><p>수집 식단 {dailySummary?.mealStatistics?.mealSamples.toLocaleString()||'—'}건 · 평균 열량 {dailySummary?.mealStatistics?.averageCalories==null?'미제공':`${dailySummary.mealStatistics.averageCalories} kcal`} · 열량 표본 {dailySummary?.mealStatistics?.calorieSamples||0}건</p><div className="education-table-wrap"><table><thead><tr><th>메뉴</th><th>출현 횟수</th></tr></thead><tbody>{dailySummary?.mealStatistics?.topMenus.map(row=><tr key={row.menu}><td>{row.menu}</td><td>{row.count.toLocaleString()}</td></tr>)}</tbody></table></div><h3>알레르기 표시 식단 수</h3><p>{Object.entries(dailySummary?.mealStatistics?.allergyMeals||{}).map(([code,count])=>`${code}번: ${count}건`).join(' · ')||'수집된 알레르기 표시 없음'}</p><p>메뉴명에서 알레르기 번호를 제거해 동일 표기를 집계합니다. 선호도·인기도 순위가 아니며 학교별 표기 차이는 유지합니다.</p></section>
  <section className="education-page-copy"><h2>앞으로 30일 학교 일정</h2><div className="education-table-wrap"><table><thead><tr><th>날짜</th><th>일정명</th><th>수집된 학교 수</th></tr></thead><tbody>{dailySummary?.events?.map(row=><tr key={`${row.date}-${row.name}`}><td>{row.date}</td><td>{row.name}</td><td>{row.schoolCount.toLocaleString()}</td></tr>)}</tbody></table></div></section>
  <section className="education-page-copy"><h2>급식·학사일정 집계 기준</h2><p>급식 건수는 날짜별 조식·중식·석식 식단을 합산합니다. 학사일정은 오늘부터 30일 안에 등록된 행사, 시험, 방학과 재량휴업일 등을 포함합니다.</p><p>학교별 일정 변경은 각 학교 안내를 우선하세요. NEIS 데이터를 일배치로 저장하고 중복 키를 제거해 집계합니다. 오늘 갱신 성공 {dailySummary?.freshSchools||0} / {dailySummary?.totalSchools||0}개교 · 수집 실패 {dailySummary?.failedSchools||0}개교입니다. 전체 수집 전에는 전국 확정 통계가 아닙니다.</p></section></>}
  {(view==='hub'||view==='regions')&&<section className="education-kpis" aria-label="전국 요약"><article><small>수집된 학생</small><b>{disclosure?.metrics.some(row=>row.metric==='student_count')?`${Math.round(students).toLocaleString()}명`:'미수집'}</b><span>{disclosure?.year||year}년 학교알리미</span></article><article><small>수집된 교원</small><b>{disclosure?.metrics.some(row=>row.metric==='teacher_count')?`${Math.round(teachers).toLocaleString()}명`:'미수집'}</b><span>직위별 교원 공시</span></article><article><small>학급당 학생 수</small><b>{ratios.some(row=>row.denominatorMetric==='class_count')?`${(ratios.filter(row=>row.denominatorMetric==='class_count').reduce((sum,row)=>sum+Number(row.numerator),0)/ratios.filter(row=>row.denominatorMetric==='class_count').reduce((sum,row)=>sum+Number(row.denominator),0)).toFixed(1)}명`:'미수집'}</b><span>수집 범위 가중평균</span></article><article><small>도서관 장서</small><b>{disclosure?.metrics.some(row=>row.metric==='library_books')?`${Math.round(books).toLocaleString()}권`:'미수집'}</b><span>수집된 학교 합계</span></article></section>}
  {view==='collection'&&dailySummary&&<section className="collection-progress" aria-label="NEIS 일일 수집 상태"><div><small>NEIS 급식·학사일정 순환 수집</small><b>{dailySummary.batch.lastStatus}</b></div><progress value={dailySummary.batch.nextSchoolOffset} max={dailySummary.totalSchools}/><span>{dailySummary.batch.completedCycles>0?`${dailySummary.batch.completedCycles.toLocaleString()}회 전체 순환 완료`:`${dailySummary.batch.nextSchoolOffset.toLocaleString()} / ${dailySummary.totalSchools.toLocaleString()}개교 처리`}</span></section>}
  {view==='collection'&&disclosure&&<section className="collection-progress" aria-label="학교알리미 수집 상태"><div><small>학교알리미 최근 3년 전체 공시 백필</small><b>{disclosure.batch.lastStatus}</b></div><progress value={disclosure.batch.nextIndex} max={disclosure.totalScopes}/><span>{disclosure.batch.completedCycles>0?'최근 3년 전체 공시 수집 완료 후 갱신 중':`${disclosure.batch.nextIndex.toLocaleString()} / ${disclosure.totalScopes.toLocaleString()}개 범위 처리`}</span></section>}
  {view==='regions'&&<div className="education-grid"><section className="education-panel education-ranking"><header><div><small>REGIONAL COMPARISON</small><h2>{year}년 지역별 {metricInfo[metric].label}</h2></div><span>높은 순</span></header><div className="education-bars">{sorted.map((region,index)=>{const value=displayValue(region);return <article key={region.name}><span className="rank">{index+1}</span><b>{region.name}</b><div><i style={{width:`${Math.max(value/max*100,3)}%`}}/></div><strong>{metric==='schools'?((liveSchoolCounts[region.name]===undefined)?'미수집':metricInfo[metric].format(value)):(disclosure?.metrics.some(row=>matchesRegion(region,row.region)&&row.metric===(metric==='students'?'student_count':'class_count'))?metricInfo[metric].format(value):'미수집')}</strong></article>})}{sorted.length===0&&<p className="education-empty">일치하는 지역이 없습니다.</p>}</div></section>
   <aside className="education-panel education-insight"><header><div><small>COLLECTED SIGNALS</small><h2>현재 수집 범위</h2></div></header><article className="increase"><span>학생 수 최다 지역</span><b>{studentRanking[0]?.region.name||'수집 대기'}</b><strong>{studentRanking[0]?`${Math.round(studentRanking[0].value).toLocaleString()}명`:'-'}</strong><p>현재까지 학교알리미 백필이 완료된 범위의 합계입니다.</p></article><article><span>학급당 학생 수 최다</span><b>{densityRanking[0]?.region.name||'수집 대기'}</b><strong>{densityRanking[0]?`${densityRanking[0].value.toFixed(1)}명`:'-'}</strong><p>학생 수 합계를 학급 수 합계로 나눈 가중평균입니다.</p></article><a href="#methodology">집계 기준 확인 →</a></aside></div>}
  <section className="education-method" id="methodology"><div><small>DATA METHODOLOGY</small><h2>공식 데이터와 집계 기준</h2></div><div className="education-sources"><article><b>NEIS 교육정보 개방 포털</b><span>학교 기본정보 · 학사일정 · 급식</span></article><article><b>학교알리미</b><span>학생 · 교원 · 시설 · 교육여건</span></article><article><b>교육통계서비스</b><span>장기 시계열 추가 연동 예정 (현재 미연동)</span></article></div><p>학교를 임의로 점수화하지 않고 원자료, 기준 연도와 계산 방식을 함께 공개합니다.</p></section>
  </main><TopButton/></div>
}
