import {useEffect,useState} from 'react'
import {educationApi,type EducationTrends} from './api'
import SiteHeader from './SiteHeader'
import EducationNav from './EducationNav'
import TopButton from './TopButton'

export default function EducationTrendPage(){
 const [regionInput,setRegionInput]=useState('')
 const [year,setYear]=useState(new Date().getFullYear()),[region,setRegion]=useState(''),[kind,setKind]=useState(''),[data,setData]=useState<EducationTrends|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 useEffect(()=>{document.title='학생 수 연도별 추이·시군구 증감 | WonderLife';document.querySelector('meta[name="description"]')?.setAttribute('content','최근 3년 학생·학급·교원 수와 동일 학교 기준 시군구별 학생 증감을 확인하세요.');let link=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=window.location.origin+'/data/education/trends'},[])
 useEffect(()=>{let active=true;setLoading(true);setError('');educationApi.trends(year,region,kind).then(value=>{if(active)setData(value)}).catch(e=>{if(active){setData(null);setError(e instanceof Error?e.message:'조회 실패')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[year,region,kind])
 return <div className="app"><SiteHeader/><main className="education-page"><header className="education-heading"><div><p className="eyebrow">MATCHED SCHOOL TRENDS</p><h1>학생 수 추이·시군구 증감</h1><p>수집 학교가 달라 생기는 착시를 줄이기 위해 증감은 두 연도에 모두 공시된 동일 학교만 비교합니다.</p></div></header><EducationNav/><section className="education-toolbar"><label><span>최근 연도</span><select value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:3},(_,i)=>new Date().getFullYear()-i).map(y=><option key={y}>{y}</option>)}</select></label><label><span>지역 코드</span><input value={regionInput} onChange={e=>{if(/^[0-9]{0,10}$/.test(e.target.value))setRegionInput(e.target.value)}} onBlur={()=>{if(regionInput===''||/^[0-9]{2,10}$/.test(regionInput))setRegion(regionInput)}} placeholder="11, 11140 등"/></label><label><span>학교급</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">전체</option><option value="02">초등학교</option><option value="03">중학교</option><option value="04">고등학교</option><option value="05">특수학교</option><option value="06">그 외</option><option value="07">각종학교</option></select></label></section>{error&&<p role="alert">{error}</p>}{loading?<p role="status">통계 조회 중…</p>:data&&<><section className="education-page-copy"><h2>최근 3년 수집 합계</h2><div className="education-table-wrap"><table><thead><tr><th>연도</th><th>학생 수 (학교 표본)</th><th>학급 수 (학교 표본)</th><th>교원 수 (학교 표본)</th></tr></thead><tbody>{data.annual.map(row=><tr key={row.year}><td>{row.year}</td><td>{row.studentSchools?`${row.students.toLocaleString()}명 (${row.studentSchools}개교)`:'미수집'}</td><td>{row.classSchools?`${row.classes.toLocaleString()}학급 (${row.classSchools}개교)`:'미수집'}</td><td>{row.teacherSchools?`${row.teachers.toLocaleString()}명 (${row.teacherSchools}개교)`:'미수집'}</td></tr>)}</tbody></table></div>{data.annual.length===0&&<p>수집된 연도별 지표가 없습니다.</p>}<p>위 합계는 연도마다 표본이 달라 직접적인 증감률 계산에 사용하지 않습니다.</p></section><section className="education-page-copy"><h2>{year-1} → {year} 동일 학교 학생 수 비교</h2><div className="education-table-wrap"><table><thead><tr><th>현재 시군구 코드</th><th>비교 학교</th><th>이전 학생</th><th>현재 학생</th><th>증감</th><th>증감률</th></tr></thead><tbody>{data.changes.map(row=><tr key={row.region}><td>{row.region}</td><td>{row.matchedSchools}개교</td><td>{row.previousStudents.toLocaleString()}</td><td>{row.currentStudents.toLocaleString()}</td><td>{(row.currentStudents-row.previousStudents).toLocaleString()}</td><td>{row.previousStudents>0?`${((row.currentStudents/row.previousStudents-1)*100).toFixed(1)}%`:'계산 불가'}</td></tr>)}</tbody></table></div>{data.changes.length===0&&<p>두 연도에 모두 수집된 동일 학교가 없어 아직 비교할 수 없습니다. <a href="/data/education/collection-status">백필 현황</a>을 확인하세요.</p>}<p>현재 연도 행정구역으로 분류합니다. 신설·폐교 학교는 동일 학교 표본에 포함되지 않으며, 지역 전체 인구 변화나 모든 학교의 증감을 뜻하지 않습니다.</p></section></>}</main><TopButton/></div>
}
