import {useEffect,useState} from 'react'
import {educationApi,type EducationDisclosurePage} from './api'
import {apiTypeLabels} from './educationContent'
import SiteHeader from './SiteHeader'
import EducationNav from './EducationNav'
import TopButton from './TopButton'

export default function EducationDisclosurePage(){
 const initial=new URLSearchParams(window.location.search)
 const [year,setYear]=useState(String(new Date().getFullYear())),[type,setType]=useState(''),[region,setRegion]=useState(''),[name,setName]=useState(initial.get('name')||'')
 const [types,setTypes]=useState<string[]>([]),[result,setResult]=useState<EducationDisclosurePage|null>(null),[page,setPage]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(''),[filters,setFilters]=useState({year:Number(year),type:'',region:'',name})
 useEffect(()=>{document.title='학교알리미 전체 공시 자료 | WonderLife';document.querySelector('meta[name="description"]')?.setAttribute('content','학교알리미 공시 원자료를 연도, API 유형, 지역과 학교명으로 조회합니다.');let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=window.location.origin+'/data/education/disclosures';educationApi.disclosureTypes().then(setTypes).catch(()=>setError('공시 목록을 불러오지 못했습니다.'))},[])
 useEffect(()=>{let active=true;setLoading(true);setError('');educationApi.disclosures({...filters,page}).then(value=>{if(active)setResult(value)}).catch(e=>{if(active){setResult(null);setError(e instanceof Error?e.message:'자료 조회 실패')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[filters,page])
 return <div className="app"><SiteHeader/><main className="education-page"><header className="education-heading"><div><p className="eyebrow">SCHOOL DISCLOSURE DATA</p><h1>학교알리미 전체 공시 자료</h1><p>저장된 공시 원문을 모든 필드와 함께 조회합니다. 미수집은 실제 0건과 다를 수 있습니다.</p></div></header><EducationNav/>
 <form className="education-toolbar" onSubmit={e=>{e.preventDefault();setPage(0);setFilters({year:Number(year),type,region,name:name.trim()})}}><label><span>공시 연도</span><select value={year} onChange={e=>setYear(e.target.value)}>{Array.from({length:3},(_,i)=>String(new Date().getFullYear()-i)).map(y=><option key={y}>{y}</option>)}</select></label><label><span>공시 유형</span><select value={type} onChange={e=>setType(e.target.value)}><option value="">전체 유형</option>{types.map(code=><option key={code} value={code}>{code} · {apiTypeLabels[code]||'공시 원자료'}</option>)}</select></label><label><span>지역 코드</span><input value={region} onChange={e=>setRegion(e.target.value)} placeholder="11, 11140 등" inputMode="numeric" pattern="[0-9]{2,10}"/></label><label><span>학교명</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><button className="education-action" disabled={loading}>조회</button></form>
 {error&&<p role="alert">{error}</p>}{loading?<p role="status">공시 자료 조회 중…</p>:result&&<><p>저장된 자료 {result.total.toLocaleString()}건 · {page+1}페이지</p>{result.items.length===0?<p className="education-page-copy">해당 조건의 수집된 자료가 없습니다. <a href="/data/education/collection-status">수집 현황 확인</a></p>:result.items.map((row,index)=><details className="education-disclosure-row" key={`${row.type}-${row.school}-${index}`}><summary><b>{row.name}</b><span>{row.year} · API {row.type} · {row.region}</span></summary><p>원천 학교코드 {row.school} · 수집 시각 {row.collectedAt} UTC</p><dl>{Object.entries(JSON.parse(row.payload) as Record<string,unknown>).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value??'—')}</dd></div>)}</dl></details>)}<div className="education-pagination"><button disabled={page===0||loading} onClick={()=>setPage(v=>v-1)}>이전</button><span>{page+1} / {Math.max(1,Math.ceil(result.total/result.pageSize))}</span><button disabled={(page+1)*result.pageSize>=result.total||loading} onClick={()=>setPage(v=>v+1)}>다음</button></div></>}
 <section className="education-page-copy"><h2>원자료 이용 안내</h2><p>공시 유형마다 필드 정의와 단위가 다릅니다. 필드명만으로 수치를 합산하거나 학교 순위를 만들지 않습니다. 현재 화면은 정규화 지표 외의 원문 필드도 빠짐없이 제공합니다.</p><a href="https://www.schoolinfo.go.kr/ng/go/pnnggo_a01_l0.do" target="_blank" rel="noreferrer">학교알리미 API 제공목록과 필드 설명 ↗</a></section></main><TopButton/></div>
}
