import {useEffect,useMemo,useState} from 'react'
type Props={onCalculated:(title:string,input:unknown,result:unknown)=>void;restoreInput?:Record<string,unknown>|null}
const keys=['ownCash','deposit','sale','savings','gift','mortgage','credit','other'] as const
const labels:Record<typeof keys[number],string>={ownCash:'보유 현금',deposit:'임대보증금 회수',sale:'부동산 처분대금',savings:'예금·적금 만기',gift:'증여·상속·가족 지원',mortgage:'주택담보대출',credit:'신용·기타 대출',other:'기타 자금'}
const raw=(v:string)=>Number(v.replaceAll(',',''))||0,won=(v:string)=>raw(v)*10000,from=(v:unknown)=>String(Math.round(Number(v||0)/10000)),fmt=(v:string)=>{const x=v.replaceAll(',','').replace(/[^0-9.-]/g,'');return x?x.replace(/\B(?=(\d{3})+(?!\d))/g,','):''},show=(v:number)=>`${Math.round(v/10000).toLocaleString()}만원`
const Money=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="field"><span>{label}</span><span className="input-unit"><input inputMode="numeric" value={fmt(value)} onChange={e=>set(fmt(e.target.value))}/><em>만원</em></span></label>
export default function FundingSourceCalculator({onCalculated,restoreInput}:Props){
 const [price,setPrice]=useState(''),[costs,setCosts]=useState(''),[values,setValues]=useState<Record<typeof keys[number],string>>(()=>Object.fromEntries(keys.map(k=>[k,''])) as Record<typeof keys[number],string>),[notes,setNotes]=useState(''),[result,setResult]=useState<{required:number;total:number;gap:number;debt:number;own:number}|null>(null),[error,setError]=useState('')
 useEffect(()=>{if(!restoreInput)return;setPrice(from(restoreInput.price));setCosts(from(restoreInput.costs));setValues(Object.fromEntries(keys.map(k=>[k,from(restoreInput[k])])) as Record<typeof keys[number],string>);setNotes(String(restoreInput.notes||''));setResult(null)},[restoreInput])
 const total=useMemo(()=>keys.reduce((s,k)=>s+won(values[k]),0),[values]),required=won(price)+won(costs)
 const calculate=()=>{if(won(price)<=0){setError('0보다 큰 주택가격을 입력해 주세요.');setResult(null);return}const input={price:won(price),costs:won(costs),...Object.fromEntries(keys.map(k=>[k,won(values[k])])),notes};const debt=won(values.mortgage)+won(values.credit),own=total-debt,next={required,total,gap:total-required,debt,own};setResult(next);setError('');onCalculated('아파트 자금출처 점검',input,{...next,main:next.gap>=0?`여유자금 ${show(next.gap)}`:`부족자금 ${show(-next.gap)}`})}
 const reset=()=>{setPrice('');setCosts('');setValues(Object.fromEntries(keys.map(k=>[k,''])) as Record<typeof keys[number],string>);setNotes('');setResult(null);setError('')}
 return <div className="housing-planner funding-check"><div className="planner-intro"><b>주택 취득에 사용할 자금 출처를 항목별로 점검하세요.</b><p>공식 신고서를 대신하지 않으며 실제 제출 대상과 증빙은 관할 기관에서 확인해야 합니다.</p></div><fieldset><legend>필요 자금</legend><div className="form-grid compact"><Money label="주택가격" value={price} set={setPrice}/><Money label="취득세·중개보수 등 부대비용" value={costs} set={setCosts}/></div></fieldset><fieldset><legend>자금 출처</legend><div className="form-grid compact">{keys.map(k=><Money key={k} label={labels[k]} value={values[k]} set={v=>setValues(old=>({...old,[k]:v}))}/>)}</div><label className="field"><span>자금 출처 메모·증빙 계획</span><textarea rows={3} maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="예: 예금 잔액증명서, 임대차계약서, 대출 약정서"/></label></fieldset><div className="funding-live"><span>필요 자금 <b>{show(required)}</b></span><span>입력한 출처 합계 <b>{show(total)}</b></span></div><button className="planner-reset" onClick={reset}>초기화</button><button className="primary planner-submit" onClick={calculate}>자금 출처 점검하기</button>{error&&<p className="planner-error">{error}</p>}{result&&<><section className="planner-summary"><div><small>{result.gap>=0?'확보 후 여유자금':'추가로 필요한 자금'}</small><strong>{show(Math.abs(result.gap))}</strong><p>입력한 자금 출처와 주택가격·부대비용의 단순 비교입니다.</p></div><dl><div><dt>총 필요 자금</dt><dd>{show(result.required)}</dd></div><div><dt>자금 출처 합계</dt><dd>{show(result.total)}</dd></div><div><dt>자기자금</dt><dd>{show(result.own)}</dd></div><div><dt>차입금</dt><dd>{show(result.debt)}</dd></div></dl></section><aside className="planner-notice"><b>확인할 증빙 예시</b><ul><li>예금잔액증명서·이체내역</li><li>부동산 매매계약서·임대차계약서</li><li>금융기관 대출 약정서</li><li>증여·상속 관련 신고 및 납부 자료</li></ul><p>실제 거래가격 6억원 이상 주택 등은 자금조달계획서 제출 대상이 될 수 있으므로 최신 공식 기준을 확인하세요.</p></aside></>}</div>
}
