import {useEffect,useMemo,useState} from 'react'
import {housingPlan,type HousingPlanInput,type HousingPlanResult,type HousingPlanRow} from './housingPlan'

type ExtraEvent={id:string;month:string;amount:string;memo:string}
type Period='month'|'quarter'|'half'|'year'
type StoredInput=Record<string,unknown>
const NOTE_MAX=80
const nv=(v:string)=>Number(v.replaceAll(',',''))||0
const wonFromMan=(v:string)=>nv(v)*10000
const manFromWon=(v:unknown)=>String(Math.round(Number(v||0)/10000))
const grouped=(v:string)=>{const raw=v.replaceAll(',','').replace(/[^0-9.-]/g,'');if(!raw)return '';const [a,b]=raw.split('.');return a.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(raw.includes('.')?'.'+(b??''):'')}
const man=(v:number)=>`${Math.round(v/10000).toLocaleString('ko-KR')}만원`
const monthPlus=(base:string,n:number)=>{const [y,m]=base.split('-').map(Number),d=new Date(y,m-1+n,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const currentMonth=(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`})()
const Money=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="field"><span>{label}</span><span className="input-unit"><input type="text" inputMode="numeric" value={grouped(value)} onChange={e=>set(grouped(e.target.value))}/><em>만원</em></span></label>
const NumberField=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="field"><span>{label}</span><input type="text" inputMode="decimal" value={grouped(value)} onChange={e=>set(grouped(e.target.value))}/></label>
const Text=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><label className="field"><span>{label}</span><input type="text" value={value} placeholder="YYYY-MM" onChange={e=>set(e.target.value)}/></label>
const periodKey=(month:string,p:Period)=>{const [y,m]=month.split('-').map(Number);return p==='month'?month:p==='quarter'?`${y}년 ${Math.ceil(m/3)}분기`:p==='half'?`${y}년 ${m<=6?'상반기':'하반기'}`:`${y}년`}
const aggregate=(rows:HousingPlanRow[],p:Period)=>{if(p==='month')return rows;const groups=new Map<string,HousingPlanRow>();for(const row of rows){const key=periodKey(row.month,p),old=groups.get(key);groups.set(key,old?{...old,saving:old.saving+row.saving,extra:old.extra+row.extra,property:old.property+row.property,housing:old.housing+row.housing,closing:row.closing,memo:[old.memo,row.memo].filter(Boolean).join(' · ')}:{...row,month:key})}return [...groups.values()]}

export default function HousingPlanCalculator({onCalculated,restoreInput}:{onCalculated:(title:string,input:unknown,result:unknown)=>void;restoreInput?:StoredInput|null}){
 const [startMonth,setStartMonth]=useState(currentMonth),[moveInMonth,setMoveInMonth]=useState(monthPlus(currentMonth,48)),[firstInterimMonth,setFirstInterimMonth]=useState(monthPlus(currentMonth,4))
 const [initialCash,setInitialCash]=useState(''),[monthlySaving,setMonthlySaving]=useState(''),[includeStartMonthSaving,setIncludeStartMonthSaving]=useState(false),[price,setPrice]=useState(''),[optionCost,setOptionCost]=useState('')
 const [contractRate,setContractRate]=useState('10'),[includeContractAtStart,setIncludeContractAtStart]=useState(true),[interimRate,setInterimRate]=useState('60'),[interimCount,setInterimCount]=useState('6'),[interimInterval,setInterimInterval]=useState('8'),[annualLoanRate,setAnnualLoanRate]=useState('4.3'),[balanceRate,setBalanceRate]=useState('30'),[acquisitionTaxRate,setAcquisitionTaxRate]=useState('3.3'),[incidentalCost,setIncidentalCost]=useState('')
 const [useInterimLoan,setUseInterimLoan]=useState(true),[loanRounds,setLoanRounds]=useState<number[]>([1,2,3,4])
 const [events,setEvents]=useState<ExtraEvent[]>([]),[result,setResult]=useState<HousingPlanResult|null>(null),[error,setError]=useState(''),[period,setPeriod]=useState<Period>('month')

 useEffect(()=>{if(!restoreInput)return;const sm=(k:string,s:(v:string)=>void)=>s(manFromWon(restoreInput[k]));setStartMonth(String(restoreInput.startMonth||currentMonth));setMoveInMonth(String(restoreInput.moveInMonth||monthPlus(currentMonth,48)));setFirstInterimMonth(String(restoreInput.firstInterimMonth||monthPlus(currentMonth,4)));sm('initialCash',setInitialCash);sm('monthlySaving',setMonthlySaving);sm('price',setPrice);sm('optionCost',setOptionCost);sm('incidentalCost',setIncidentalCost);setContractRate(String(restoreInput.contractRate??10));setInterimRate(String(restoreInput.interimRate??60));setInterimCount(String(restoreInput.interimCount??6));setInterimInterval(String(restoreInput.interimInterval??8));setAnnualLoanRate(String(restoreInput.annualLoanRate??4.3));setBalanceRate(String(restoreInput.balanceRate??30));setAcquisitionTaxRate(String(restoreInput.acquisitionTaxRate??3.3));const count=Number(restoreInput.loanInstallments??4);const rounds=Array.isArray(restoreInput.loanRounds)?restoreInput.loanRounds.map(Number).filter(Number.isFinite):Array.from({length:count},(_,i)=>i+1);setUseInterimLoan(restoreInput.useInterimLoan===undefined?rounds.length>0:Boolean(restoreInput.useInterimLoan));setLoanRounds(rounds);const old=Array.isArray(restoreInput.manualEvents)?restoreInput.manualEvents as {month:string;amount:number;memo:string}[]:[];setEvents(old.map(x=>({id:crypto.randomUUID(),month:x.month,amount:manFromWon(x.amount),memo:String(x.memo||'').slice(0,NOTE_MAX)})));const savedPeriod=String(restoreInput.viewPeriod||'month');setPeriod((['month','quarter','half','year'].includes(savedPeriod)?savedPeriod:'month') as Period);try{setResult(housingPlan(restoreInput as unknown as HousingPlanInput));setError('')}catch{setResult(null);setError('불러온 입력값을 확인한 뒤 다시 계산해 주세요.')}},[restoreInput])
 useEffect(()=>{if(restoreInput)setIncludeStartMonthSaving(Boolean(restoreInput.includeStartMonthSaving))},[restoreInput])
 useEffect(()=>{if(restoreInput)setIncludeContractAtStart(restoreInput.includeContractAtStart!==false)},[restoreInput])

 const displayRows=useMemo(()=>aggregate(result?.rows||[],period),[result,period])
 const normalizedEvents=(source:ExtraEvent[])=>source.filter(x=>x.amount||x.memo).map((x,i)=>{if(!/^\d{4}-\d{2}$/.test(x.month))throw new Error(`추가 자금 ${i+1}행의 월을 확인해 주세요.`);return {month:x.month,amount:wonFromMan(x.amount),memo:x.memo.slice(0,NOTE_MAX)}})
 const makeInput=(source:ExtraEvent[])=>{const selected=useInterimLoan?loanRounds.filter(x=>x<=Math.max(0,Math.floor(nv(interimCount)))):[];return {startMonth,moveInMonth,initialCash:wonFromMan(initialCash),monthlySaving:wonFromMan(monthlySaving),includeStartMonthSaving,additionalFunds:0,depositReturn:0,price:wonFromMan(price),optionCost:wonFromMan(optionCost),contractRate:nv(contractRate),includeContractAtStart,interimRate:nv(interimRate),interimCount:nv(interimCount),loanInstallments:selected.length,loanRounds:selected,useInterimLoan,firstInterimMonth,interimInterval:nv(interimInterval),annualLoanRate:nv(annualLoanRate),balanceRate:nv(balanceRate),acquisitionTaxRate:nv(acquisitionTaxRate),incidentalCost:0,manualEvents:normalizedEvents(source),viewPeriod:period}}
 const calculate=(source=events,save=true)=>{try{if(!/^\d{4}-\d{2}$/.test(startMonth)||!/^\d{4}-\d{2}$/.test(moveInMonth)||!/^\d{4}-\d{2}$/.test(firstInterimMonth))throw new Error('날짜는 YYYY-MM 형식으로 입력해 주세요.');if(nv(price)<=0)throw new Error('0보다 큰 분양가를 입력해 주세요.');const input=makeInput(source),next=housingPlan(input);setResult(next);setError('');if(save)onCalculated('아파트 자금 계획기',input,{...next,main:`입주 시 부족자금 ${man(next.requiredMortgage)}`})}catch(e){if(save)setResult(null);setError(e instanceof Error?e.message:'입력값을 확인해 주세요.')}}
 const setMonthEvent=(month:string,key:'amount'|'memo',value:string)=>{const old=events.find(x=>x.month===month),next=old?events.map(x=>x.id===old.id?{...x,[key]:value}:x):[...events,{id:crypto.randomUUID(),month,amount:key==='amount'?value:'',memo:key==='memo'?value:''}];setEvents(next);calculate(next,false)}
 const toggleRound=(round:number)=>setLoanRounds(old=>old.includes(round)?old.filter(x=>x!==round):[...old,round].sort((a,b)=>a-b))
 const eventFor=(month:string)=>events.find(x=>x.month===month)
 const roundCount=Math.max(0,Math.min(12,Math.floor(nv(interimCount))))
 const reset=()=>{setStartMonth(currentMonth);setMoveInMonth(monthPlus(currentMonth,48));setFirstInterimMonth(monthPlus(currentMonth,4));setInitialCash('');setMonthlySaving('');setIncludeStartMonthSaving(false);setPrice('');setOptionCost('');setContractRate('10');setIncludeContractAtStart(true);setInterimRate('60');setInterimCount('6');setInterimInterval('8');setAnnualLoanRate('4.3');setBalanceRate('30');setAcquisitionTaxRate('3.3');setIncidentalCost('');setUseInterimLoan(true);setLoanRounds([1,2,3,4]);setEvents([]);setResult(null);setError('');setPeriod('month')}

 return <div className="housing-planner"><div className="planner-intro"><b>내 조건으로 입주일까지의 현금 흐름을 확인하세요.</b><p>입력과 결과는 만원 단위이며 내부 계산은 원 단위로 처리합니다.</p></div>
 <fieldset><legend>일정과 보유 자금</legend><div className="form-grid compact"><Text label="계산 시작월" value={startMonth} set={setStartMonth}/><Text label="입주 예정월" value={moveInMonth} set={setMoveInMonth}/><Money label="월초 보유 현금" value={initialCash} set={setInitialCash}/><div className="saving-field"><Money label="매월 저축액" value={monthlySaving} set={setMonthlySaving}/><label className="saving-start-toggle"><input type="checkbox" checked={includeStartMonthSaving} onChange={e=>setIncludeStartMonthSaving(e.target.checked)}/><span>계산 시작월부터 저축액 반영</span></label></div></div></fieldset>
 <fieldset><legend>계약·입주 대금</legend><div className="form-grid compact"><Money label="분양가" value={price} set={setPrice}/><Money label="옵션비 총액" value={optionCost} set={setOptionCost}/><div className="saving-field"><NumberField label="계약금 비율 (%)" value={contractRate} set={setContractRate}/><label className="saving-start-toggle"><input type="checkbox" checked={includeContractAtStart} onChange={e=>setIncludeContractAtStart(e.target.checked)}/><span>계산 시작월에 계약금 반영</span></label></div><NumberField label="잔금 비율 (%)" value={balanceRate} set={setBalanceRate}/><NumberField label="예상 취득 관련 세율 (%)" value={acquisitionTaxRate} set={setAcquisitionTaxRate}/></div></fieldset>
 <fieldset><legend>중도금 계획</legend><div className="form-grid compact"><NumberField label="중도금 총 비율 (%)" value={interimRate} set={setInterimRate}/><NumberField label="중도금 총 회차" value={interimCount} set={v=>{setInterimCount(v);setLoanRounds(old=>old.filter(x=>x<=nv(v)))}}/><Text label="중도금 첫 납부월" value={firstInterimMonth} set={setFirstInterimMonth}/><NumberField label="중도금 간격 (개월)" value={interimInterval} set={setInterimInterval}/></div><label className="loan-toggle"><input type="checkbox" checked={useInterimLoan} onChange={e=>setUseInterimLoan(e.target.checked)}/><span>중도금 대출 사용</span></label><div className={`loan-settings${useInterimLoan?'':' disabled'}`} aria-disabled={!useInterimLoan}><NumberField label="중도금 대출 연이율 (%)" value={annualLoanRate} set={setAnnualLoanRate}/><div className="loan-rounds"><b>대출받을 회차</b><div>{Array.from({length:roundCount},(_,i)=>i+1).map(round=><label key={round}><input type="checkbox" disabled={!useInterimLoan} checked={useInterimLoan&&loanRounds.includes(round)} onChange={()=>toggleRound(round)}/><span>{round}회차</span></label>)}</div><small>선택하지 않은 회차는 현금 납부로 계산합니다.</small></div></div></fieldset>
 <button className="planner-reset" type="button" onClick={reset}>초기화</button>
 <button className="primary planner-submit" onClick={()=>calculate()}>자금 계획 계산하기</button>{error&&<p className="planner-error" role="alert">{error}</p>}{result&&<><section className="planner-summary"><div><small>입주 시 부족자금</small><strong>{man(result.requiredMortgage)}</strong><p>대출 승인액이 아니라 추가로 마련해야 하는 예상 금액입니다.</p></div><dl>{[['계약금',result.contract],['중도금 대출 원금',result.interimLoanPrincipal],['중도금 예상 이자',result.interimInterest],['분양 잔금',result.balance],['예상 취득 관련 세금',result.acquisitionTax],['총 예상 사업비',result.totalProjectCost]].map(([l,v])=><div key={String(l)}><dt>{l}</dt><dd>{man(Number(v))}</dd></div>)}</dl></section><div className="period-toggle">{([['month','월별'],['quarter','분기'],['half','반기'],['year','연도']] as [Period,string][]).map(([v,l])=><button className={period===v?'selected':''} onClick={()=>setPeriod(v)} key={v}>{l}</button>)}</div><p className="planner-table-help">월별 보기에서는 추가 자금·수익과 비고를 표에 바로 입력할 수 있습니다. 수입은 양수, 지출은 음수로 입력하세요.</p><div className="planner-table table-wrap"><table><thead><tr><th>기간</th><th>기초 현금</th><th>저축</th><th>추가 자금·수익</th><th>계약금·중도금·입주비용</th><th>기말 현금</th><th>비고</th></tr></thead><tbody>{displayRows.map(r=>{const manual=period==='month'?eventFor(r.month):undefined;return <tr className={r.memo?'event-row':''} key={r.month}><td>{r.month}</td><td>{man(r.opening)}</td><td>{man(r.saving)}</td><td>{period==='month'?<span className="table-money-input"><input aria-label={`${r.month} 추가 자금·수익`} inputMode="numeric" value={grouped(manual?.amount||'')} placeholder="0" onChange={e=>setMonthEvent(r.month,'amount',grouped(e.target.value))}/><em>만원</em></span>:man(r.extra)}</td><td>{man(r.property)}</td><td className={r.closing<0?'shortage':''}>{man(r.closing)}</td><td>{period==='month'?<div className="table-note-cell"><span>{r.memo.replace(manual?.memo||'','').replace(/^ · | · $/g,'')||'—'}</span><input aria-label={`${r.month} 비고`} maxLength={NOTE_MAX} value={manual?.memo||''} placeholder="직접 입력" onChange={e=>setMonthEvent(r.month,'memo',e.target.value)}/></div>:r.memo||'—'}</td></tr>})}</tbody></table></div><aside className="planner-notice"><b>계산 전 꼭 확인하세요</b><ul><li>취득 관련 세금은 주택 수, 지역, 취득가액과 감면 여부에 따라 달라집니다.</li><li>대출 이자는 월 단위 단리 추정이며 실제 실행 조건과 다를 수 있습니다.</li><li>부족자금은 대출 가능액이 아닙니다.</li></ul></aside></>}</div>
}
