export type SiteLink={name:string;url:string;category:string;description:string;tags:string[];notice?:string}

export const siteLinkCategories=['전체','포털·검색','공공·행정','금융·경제','교통·여행','가격·쇼핑','커뮤니티','취업·생활','뉴스·날씨']

export const siteLinks:SiteLink[]=[
 {name:'네이버',url:'https://www.naver.com/',category:'포털·검색',description:'검색, 뉴스, 지도, 쇼핑과 생활 서비스를 제공하는 국내 포털입니다.',tags:['검색','포털']},
 {name:'다음',url:'https://www.daum.net/',category:'포털·검색',description:'검색, 뉴스, 카페와 다양한 콘텐츠를 제공하는 국내 포털입니다.',tags:['검색','포털','카페']},
 {name:'네이트',url:'https://www.nate.com/',category:'포털·검색',description:'뉴스, 검색과 커뮤니티 콘텐츠를 제공하는 국내 포털입니다.',tags:['뉴스','검색','포털']},
 {name:'정부24',url:'https://www.gov.kr/',category:'공공·행정',description:'민원 신청, 정부 서비스와 정책 정보를 찾는 대한민국 정부 대표 포털입니다.',tags:['민원','증명서','정부']},
 {name:'홈택스',url:'https://www.hometax.go.kr/',category:'공공·행정',description:'국세 신고·납부, 연말정산과 각종 세금 증명 업무를 처리합니다.',tags:['국세','연말정산','세금']},
 {name:'위택스',url:'https://www.wetax.go.kr/',category:'공공·행정',description:'취득세와 자동차세 등 지방세를 조회·신고·납부할 수 있습니다.',tags:['지방세','취득세','자동차세']},
 {name:'국민건강보험',url:'https://www.nhis.or.kr/',category:'공공·행정',description:'건강보험 자격, 보험료와 건강검진 관련 공식 정보를 제공합니다.',tags:['건강보험','보험료','검진']},
 {name:'국민연금공단',url:'https://www.nps.or.kr/',category:'공공·행정',description:'국민연금 가입 내역과 예상연금 관련 공식 서비스를 제공합니다.',tags:['국민연금','예상연금']},
 {name:'복지로',url:'https://www.bokjiro.go.kr/',category:'공공·행정',description:'생애주기별 복지서비스를 찾고 일부 복지급여를 신청할 수 있습니다.',tags:['복지','지원금','신청']},
 {name:'청약홈',url:'https://www.applyhome.co.kr/',category:'공공·행정',description:'아파트 청약 일정, 자격과 당첨 결과를 확인하는 공식 서비스입니다.',tags:['청약','아파트','분양']},
 {name:'인터넷등기소',url:'https://www.iros.go.kr/',category:'공공·행정',description:'부동산·법인 등기 열람과 발급 업무를 제공하는 대법원 서비스입니다.',tags:['등기','부동산','법인']},
 {name:'전자가족관계등록',url:'https://efamily.scourt.go.kr/',category:'공공·행정',description:'가족관계증명서 등 가족관계등록 증명서를 발급할 수 있습니다.',tags:['가족관계','증명서']},
 {name:'국가법령정보센터',url:'https://www.law.go.kr/',category:'공공·행정',description:'현재·과거 법령, 행정규칙과 판례 관련 자료를 검색할 수 있습니다.',tags:['법령','판례','법률']},
 {name:'워크24',url:'https://www.work24.go.kr/',category:'취업·생활',description:'구직, 고용보험, 직업훈련과 취업지원 서비스를 한곳에서 제공합니다.',tags:['구직','고용보험','직업훈련']},
 {name:'도로명주소 안내',url:'https://www.juso.go.kr/',category:'공공·행정',description:'도로명주소 검색과 영문주소 변환에 필요한 공식 정보를 제공합니다.',tags:['주소','영문주소']},
 {name:'금융감독원 파인',url:'https://fine.fss.or.kr/',category:'금융·경제',description:'금융상품과 금융회사 조회, 소비자 보호 정보를 모은 금융 포털입니다.',tags:['금융상품','금융회사','보호']},
 {name:'DART',url:'https://dart.fss.or.kr/',category:'금융·경제',description:'상장회사 등의 공시 서류를 직접 확인하는 전자공시 시스템입니다.',tags:['공시','기업','투자']},
 {name:'한국은행 ECOS',url:'https://ecos.bok.or.kr/',category:'금융·경제',description:'금리, 물가, 환율 등 한국은행 경제통계를 검색할 수 있습니다.',tags:['통계','금리','환율']},
 {name:'국가통계포털 KOSIS',url:'https://kosis.kr/',category:'금융·경제',description:'인구, 물가, 고용 등 국가승인통계를 분야별로 조회할 수 있습니다.',tags:['국가통계','인구','물가']},
 {name:'한국거래소',url:'https://www.krx.co.kr/',category:'금융·경제',description:'증권시장 정보, 상장공시와 시장 통계를 제공하는 공식 사이트입니다.',tags:['주식','시장','공시']},
 {name:'은행연합회 소비자포털',url:'https://portal.kfb.or.kr/',category:'금융·경제',description:'은행 금리와 수수료 등 금융소비자 비교 정보를 제공합니다.',tags:['은행','금리','수수료']},
 {name:'코레일',url:'https://www.letskorail.com/',category:'교통·여행',description:'KTX와 일반열차 운행 정보 및 승차권 예매 서비스를 제공합니다.',tags:['기차','KTX','예매']},
 {name:'고속버스 통합예매',url:'https://www.kobus.co.kr/',category:'교통·여행',description:'고속버스 시간표를 조회하고 승차권을 예매할 수 있습니다.',tags:['버스','시간표','예매']},
 {name:'한국도로공사',url:'https://www.ex.co.kr/',category:'교통·여행',description:'고속도로 교통정보, 통행료와 휴게소 정보를 확인할 수 있습니다.',tags:['고속도로','통행료','교통']},
 {name:'네이버지도',url:'https://map.naver.com/',category:'교통·여행',description:'장소 검색, 길찾기와 대중교통 정보를 제공하는 지도 서비스입니다.',tags:['지도','길찾기','대중교통']},
 {name:'카카오맵',url:'https://map.kakao.com/',category:'교통·여행',description:'지도, 로드뷰, 길찾기와 대중교통 정보를 확인할 수 있습니다.',tags:['지도','로드뷰','길찾기']},
 {name:'대한민국 구석구석',url:'https://korean.visitkorea.or.kr/',category:'교통·여행',description:'한국관광공사가 운영하는 국내 여행지와 축제 정보 서비스입니다.',tags:['국내여행','축제','관광']},
 {name:'인천국제공항',url:'https://www.airport.kr/',category:'교통·여행',description:'항공편, 공항 교통과 출입국 이용 정보를 확인할 수 있습니다.',tags:['공항','항공편','출입국']},
 {name:'다나와',url:'https://www.danawa.com/',category:'가격·쇼핑',description:'전자제품을 비롯한 여러 상품의 가격과 사양을 비교하는 사이트입니다.',tags:['가격비교','전자제품']},
 {name:'에누리',url:'https://www.enuri.com/',category:'가격·쇼핑',description:'쇼핑 상품의 가격 비교와 카테고리별 정보를 제공합니다.',tags:['가격비교','쇼핑']},
 {name:'네이버쇼핑',url:'https://shopping.naver.com/',category:'가격·쇼핑',description:'여러 판매처의 상품과 가격을 검색하고 비교할 수 있습니다.',tags:['쇼핑','가격비교']},
 {name:'쿠팡',url:'https://www.coupang.com/',category:'가격·쇼핑',description:'식품, 생활용품, 가전 등 다양한 상품을 판매하는 쇼핑 서비스입니다.',tags:['쇼핑','배송']},
 {name:'11번가',url:'https://www.11st.co.kr/',category:'가격·쇼핑',description:'다양한 판매자의 상품을 검색하고 구매할 수 있는 온라인 마켓입니다.',tags:['오픈마켓','쇼핑']},
 {name:'G마켓',url:'https://www.gmarket.co.kr/',category:'가격·쇼핑',description:'상품 검색과 구매 서비스를 제공하는 국내 온라인 마켓입니다.',tags:['오픈마켓','쇼핑']},
 {name:'무신사',url:'https://www.musinsa.com/',category:'가격·쇼핑',description:'패션 브랜드 상품과 스타일 콘텐츠를 제공하는 쇼핑 플랫폼입니다.',tags:['패션','브랜드','쇼핑']},
 {name:'뽐뿌',url:'https://www.ppomppu.co.kr/',category:'커뮤니티',description:'쇼핑 정보와 생활·재테크 게시판을 함께 운영하는 커뮤니티입니다.',tags:['쇼핑','핫딜','생활'],notice:'게시물 정보와 거래 조건은 원문에서 다시 확인하세요.'},
 {name:'오늘의유머',url:'https://www.todayhumor.co.kr/',category:'커뮤니티',description:'유머와 다양한 생활 주제 게시판을 제공하는 커뮤니티입니다.',tags:['유머','커뮤니티']},
 {name:'클리앙',url:'https://www.clien.net/',category:'커뮤니티',description:'IT 기기와 생활 정보를 중심으로 여러 게시판을 운영하는 커뮤니티입니다.',tags:['IT','기기','생활']},
 {name:'루리웹',url:'https://www.ruliweb.com/',category:'커뮤니티',description:'게임·취미 뉴스와 주제별 게시판을 제공하는 커뮤니티입니다.',tags:['게임','취미']},
 {name:'인벤',url:'https://www.inven.co.kr/',category:'커뮤니티',description:'게임별 뉴스, 공략과 이용자 게시판을 제공하는 게임 커뮤니티입니다.',tags:['게임','공략']},
 {name:'보배드림',url:'https://www.bobaedream.co.kr/',category:'커뮤니티',description:'자동차 정보와 중고차, 주제별 게시판을 운영하는 커뮤니티입니다.',tags:['자동차','중고차']},
 {name:'디시인사이드',url:'https://www.dcinside.com/',category:'커뮤니티',description:'다양한 관심사의 갤러리 게시판을 운영하는 커뮤니티입니다.',tags:['갤러리','커뮤니티'],notice:'게시물의 정확성과 안전성은 원문에서 확인하세요.'},
 {name:'더쿠',url:'https://theqoo.net/',category:'커뮤니티',description:'연예, 생활과 관심사별 게시판을 제공하는 커뮤니티입니다.',tags:['연예','생활']},
 {name:'에펨코리아',url:'https://www.fmkorea.com/',category:'커뮤니티',description:'축구, 게임과 여러 주제의 게시판을 운영하는 커뮤니티입니다.',tags:['축구','게임']},
 {name:'MLBPARK',url:'https://mlbpark.donga.com/',category:'커뮤니티',description:'야구를 비롯한 스포츠와 생활 주제 게시판을 제공하는 커뮤니티입니다.',tags:['야구','스포츠']},
 {name:'네이트판',url:'https://pann.nate.com/',category:'커뮤니티',description:'생활, 관계와 연예 주제의 이용자 게시판을 제공합니다.',tags:['생활','이야기']},
 {name:'사람인',url:'https://www.saramin.co.kr/',category:'취업·생활',description:'채용공고와 기업·직무 관련 취업 정보를 제공합니다.',tags:['채용','기업','취업']},
 {name:'잡코리아',url:'https://www.jobkorea.co.kr/',category:'취업·생활',description:'채용공고 검색과 취업 준비 관련 서비스를 제공합니다.',tags:['채용','취업']},
 {name:'알바몬',url:'https://www.albamon.com/',category:'취업·생활',description:'지역·업종별 아르바이트 채용정보와 구직 서비스를 제공합니다.',tags:['아르바이트','채용']},
 {name:'잡플래닛',url:'https://www.jobplanet.co.kr/',category:'취업·생활',description:'기업 정보, 채용공고와 이용자 작성 기업 후기를 제공합니다.',tags:['기업','채용','후기'],notice:'기업 후기는 작성자의 경험에 따른 정보입니다.'},
 {name:'기상청 날씨누리',url:'https://www.weather.go.kr/',category:'뉴스·날씨',description:'대한민국 기상특보, 현재 날씨와 예보를 확인하는 공식 사이트입니다.',tags:['날씨','예보','특보']},
 {name:'에어코리아',url:'https://www.airkorea.or.kr/',category:'뉴스·날씨',description:'지역별 미세먼지와 대기오염 측정 정보를 제공합니다.',tags:['미세먼지','대기']}
 ,{name:'연합뉴스',url:'https://www.yna.co.kr/',category:'뉴스·날씨',description:'국내외 주요 뉴스를 제공하는 국가기간뉴스통신사 사이트입니다.',tags:['뉴스','속보']}
 ,{name:'네이버뉴스',url:'https://news.naver.com/',category:'뉴스·날씨',description:'여러 언론사의 분야별 기사와 뉴스 검색 서비스를 제공합니다.',tags:['뉴스','언론']}
 ,{name:'다음뉴스',url:'https://news.daum.net/',category:'뉴스·날씨',description:'언론사별 주요 기사와 분야별 뉴스를 모아 제공합니다.',tags:['뉴스','언론']}
]
