CREATE TABLE tools_users (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 provider_subject VARCHAR(255) NOT NULL UNIQUE,
 email VARCHAR(320) NOT NULL,
 locale VARCHAR(10) NOT NULL DEFAULT 'ko',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE tools_calculation_histories (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL,
 calculator_type VARCHAR(40) NOT NULL,
 title VARCHAR(80) NOT NULL,
 input_json JSON NOT NULL,
 result_json JSON NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT tools_fk_history_user FOREIGN KEY(user_id) REFERENCES tools_users(id) ON DELETE CASCADE,
 INDEX tools_idx_history_user_created(user_id,created_at DESC)
);
CREATE TABLE tools_spring_session (
 PRIMARY_ID CHAR(36) NOT NULL, SESSION_ID CHAR(36) NOT NULL, CREATION_TIME BIGINT NOT NULL,
 LAST_ACCESS_TIME BIGINT NOT NULL, MAX_INACTIVE_INTERVAL INT NOT NULL, EXPIRY_TIME BIGINT NOT NULL,
 PRINCIPAL_NAME VARCHAR(100), CONSTRAINT tools_spring_session_pk PRIMARY KEY (PRIMARY_ID),
 UNIQUE INDEX tools_spring_session_ix1 (SESSION_ID), INDEX tools_spring_session_ix2 (EXPIRY_TIME), INDEX tools_spring_session_ix3 (PRINCIPAL_NAME)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
CREATE TABLE tools_spring_session_ATTRIBUTES (
 SESSION_PRIMARY_ID CHAR(36) NOT NULL, ATTRIBUTE_NAME VARCHAR(200) NOT NULL, ATTRIBUTE_BYTES BLOB NOT NULL,
 CONSTRAINT tools_spring_session_attributes_pk PRIMARY KEY (SESSION_PRIMARY_ID,ATTRIBUTE_NAME),
 CONSTRAINT tools_spring_session_attributes_fk FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES tools_spring_session(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
